### ISSUE TITLE
[Demand] Integration of Arweave Step 1

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#1057]
## Metadata

Field | Value
--- | ---
Previous Stage | N/A
Figma Link | https://www.figma.com/file/jcrvENZmip6PUR66Jz6ENb/Plugin-Attachment-by-Arweave?node-id=84%3A1
Expected UX prototype due | 2020-W24-3 (06-10)
Actual UX prototype release | -
Expected engineering due | 2020-W25-5 (06-19)
Corresponding Pull Request | N/A
Completion Version | TBD

## Catalogue

- Introduction
- Roadmap
- Documentations

## Introduction

We have joined the [Arweave](https://arweave.org) Grant program to build upon their permanent storage network to enhance the capability of our extension. 

In the first step, our mission is to integrate the functionality to interact with the Arweave network and enable file uploading and retrieving in our extension.

This allows our extension to accept general files in the encrypted posts and will largely extend the functionality. Another potential use case would be providing a secure personal cloud to store their keystores to realize the cross-device synchronization ability.

In the first step, we will need to split the work in two directions: 1. a UI/UX prototype and 2. testing the communication with the Arweave network.

Research areas:

- Decentralized Permanent Storage
- File Sharing

### Stage 1: Minimal Functionality

- [x] Insert single file in one Post.
- [x] Select file from recent files.
  - The uploading modal contains 4 most recently uploaded files. The user can click to select any.
- [x] Download & decrypt files in the landing page.

### Stage 2: Good Experience

- [x] Preview unencrypted small (≤ 2 MB) images in the Snippet (Post-Affixing Canvas).
- [x] View images in the landing page through blob URI.
- [x] View images in the landing page through \<iframe>.

### Stage 3: Full Feature Set

- [ ] Select file from upload history.
  - The list in the uploading modal can be expanded and the user can scroll the list from top to bottom.
- [ ] In-Page Video Player
- [ ] In-Page Audio Player
- [ ] Preview encrypted small (≤ 2 MB) images in the Snippet (Post-Affixing Canvas).
- [ ] Insert multiple files in one Post.

## Documentations

Link Type | URL
--- | ---
Documentation | https://confluence.dimension.chat/x/3IEf
Discussion History | https://github.com/DimensionDev/Maskbook-Talks/issues/36

### Landing Page

https://www.figma.com/file/jcrvENZmip6PUR66Jz6ENb/Plugin-Attachment-by-Arweave?node-id=84%3A0

![image](https://user-images.githubusercontent.com/2139261/84862166-3161d480-b062-11ea-8c29-e7039c56592f.png)

### Plugin Modal

https://www.figma.com/file/jcrvENZmip6PUR66Jz6ENb/Plugin-Attachment-by-Arweave?node-id=4%3A34

![image](https://user-images.githubusercontent.com/2139261/84862233-58b8a180-b062-11ea-9e79-5bc0849c075d.png)

**Comment by neruthes** [comment]
Good new brainstorming movement 🎉

**Comment by neruthes** [comment]
We are mostly ready to start working on this new plugin "Attachment by Arweave". 

- [x] Features of Plugin (Stage 1)
- [x] Plugin System Design
- [x] Data exchange between Maskbook and Plugin
- [x] Encrypted Attachment Data Structure specification
- [x] Clear Attachment Data Structure specification
- [ ] Encrypted Attachment Data Binary Serialization Format specification // @septs 
- [ ] Current file size limit // TBD 
- [ ] Cache service behavior specification // @yisiliu

**Comment by neruthes** [comment]
UX prototyping can start now. *★,°*:.☆(￣▽￣)/$:*.°★* 。 cc @OiCkilL

**Comment by Jack-Works** [comment]
> Encrypted Attachment Data Binary Serialization Format specification

ZIP with a password?

**Comment by septs** [comment]
> > Encrypted Attachment Data Binary Serialization Format specification
> 
> ZIP with a password?

based https://msgpack.com

**Comment by neruthes** [comment]
# Landing Page UX

## Introduction

## Case: Basic

A file type indicator icon is presented.

![IMG_2369](https://user-images.githubusercontent.com/2139261/84250683-de38d080-aafb-11ea-9d8e-e106ee39fa02.JPG)

## Case: Previewable Content

There will be a preview box if the file satisfies the following criteria:

- Content-Type is text/plain, image/png, image/jpeg, image/svg, image/webp
- The file size is not greater than 2 MB for image or10 KB for text.

![IMG_2371](https://user-images.githubusercontent.com/2139261/84250692-e2fd8480-aafb-11ea-973c-cc1dc8ee2825.JPG)


## Case: Need File Key

The File Key should be included in the URL as `location.hash`, but it can be missing or wrong.

If the File Key cannot satisfy the predefined File Key Hash in the landing page, it falls into this case. The user has to manually input the File Key in the box.

There should be error handling for wrong File Key being inputted.

![IMG_2370](https://user-images.githubusercontent.com/2139261/84250709-e98bfc00-aafb-11ea-933f-f643b7fe2c46.JPG)

**Comment by neruthes** [comment]
Updated Figma links and screenshots.

**Comment by septs** [comment]
landing page demo:
https://arweave.net/MyVCpKLA15lBNOKH7v5S7W8TT_Kdt6-SysTPbZnHjPE#sample

**Comment by septs** [comment]
Waiting list:
1. a dedicated arweave wallet.
2. enable remote signing server (production stage).

for @yisiliu

**Comment by Tedko** [comment]
For 1: already asked Ar team for the wallet etc.

**Comment by septs** [comment]
@yisiliu plz create `[Demand] Integration of Arweave Step 2` todo list.

**Comment by Tedko** [comment]
Will Wait Ar team for further coop (Promoting step1 etc) then will start
work on step2.
