### ISSUE TITLE
[Demand] Post Text Markup Integration & Post Text Hover Card Integration 

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1415]
## Catalogue

- [x] UI/UX
- [ ] Maskbook Core Feature
- [x] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other

## Part 1: Introduction and Background

#1399 needs additional features.

## Part 2: Problem to Solve

We have introduced the block version of Post Content Interpretation (Snippet, a.k.a. Post-Affixing Canvas "PAC"). Now we will provide an inline version of Post Content Interpretation.

## Part 3: Expected Behavior

https://confluence.dimension.chat/x/9IAf

See the "Post Text Markup Integration" section and the "Post Text Hover Card Integration" section in the documentation.

## Notes

- Related: #987.

**Comment by Jack-Works** [comment]
Dependency https://confluence.dimension.chat/display/~neruthes/2020/05/14/Maskbook%3A+Component%3A+WholePostView

**Comment by Tedko** [comment]
Demo from @OiCkilL 

![291597233160_ pic_hd](https://user-images.githubusercontent.com/6687437/90102570-7f017180-dd73-11ea-92b3-009eac1cf89a.jpg)

**Comment by neruthes** [comment]
Good demo. Looking forward to for-review version.

**Comment by Jack-Works** [comment]
this is implemented IMO
