### ISSUE TITLE
[Roadmap] auto share post to friends part 3

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#142]
# Todo: Group channel
1. [x] Set Maskbook as a Matrix client
2. [ ] Impl certificate and verify the friendship cert
3. [ ] Search key in the user group
4. [ ] Send and receive friendship cert

# Todo: Better experience
1. [ ] Background friendship detection on Facebook.com
2. [ ] Active detection

# Part 2 finished
1. [x] Accept a user group as a recipient
2. [x] Share to a group
3. [x] Append recipient when new memeber in the group

# Part 1 finished

1. [x] Recognize who are friends
2. [x] Impl virtual friend user group ( #34 )
3. [x] Add friends to user group (need 1 and 2)
4. [x] Add all people to selection by default (UI)
5. [x] Allow user group as selection target (UI, need 2)
6. [x] <del>Auto share old posts to new user in the group (DB, need 2, 3)</del>
7. [x] Impl friendship cert

**Comment by Jack-Works** [comment]
related #163

**Comment by Jack-Works** [comment]
let's leave chatroom to next pr

**Comment by Jack-Works** [comment]
ref: matrix: https://github.com/DimensionDev/Maskbook/issues/185

**Comment by neruthes** [comment]
Just wondering, for the chatroom affairs, is it supposed to be working through #168 mechanism? That model requires more research before being moved to to-do.

**Comment by Jack-Works** [comment]
> Just wondering, for the chatroom affairs, is it supposed to be working through #168 mechanism? That model requires more research before being moved to to-do.

Yes, this will base on #168

**Comment by neruthes** [comment]
> > Just wondering, for the chatroom affairs, is it supposed to be working through #168 mechanism? That model requires more research before being moved to to-do.
> 
> Yes, this will base on #168

I recommend implementing auto-share in the current post key transfer model without #168. (This needs input from @yisiliu.)

**Comment by Tedko** [comment]
@neruthes For cryptographer in our community if they want to audit or join, what's the best page for them to read

**Comment by neruthes** [comment]
> @neruthes For cryptographer in our community if they want to audit or join, what's the best page for them to read?

Do you mean general audits or component-specific investigation? Now we do not have a comprehensive documentation for cryptographic designs but #168 really needs investigation.

**Comment by Tedko** [comment]
Any updates?

**Comment by Jack-Works** [comment]
No progress yet. there're still two aspects we may improve listed in the first thread.

**Comment by Jack-Works** [comment]
@neruthes Which specification of friendship certificate should I refer to implement now?

**Comment by neruthes** [comment]
> @neruthes Which specification of friendship certificate should I refer to implement now?

The specification of ProfileGroup Membership Certificate remains to be designed...

**Comment by Jack-Works** [comment]
> > @neruthes Which specification of friendship certificate should I refer to implement now?
> 
> The specification of ProfileGroup Membership Certificate remains to be designed...

Or the latest draft that I can use as a reference

**Comment by neruthes** [comment]
> > > @neruthes Which specification of friendship certificate should I refer to implement now?
> > 
> > 
> > The specification of ProfileGroup Membership Certificate remains to be designed...
> 
> Or the latest draft that I can use as a reference

https://github.com/DimensionDev/Maskbook/wiki/UserGroup-Membership-Certificate

**Comment by Tedko** [comment]
@Jack-Works hows the status of auto share -?

**Comment by Jack-Works** [comment]
Not too much.
