### ISSUE TITLE
[Demand] Red Packet Plugin i18n

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1524]
## Catalogue

- [ ] UI/UX
- [ ] Maskbook Core Feature
- [x] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
    - /* List it here */

## Introduction and Background

Later plugins (e.g. File Service and Trader) are now i18n-ready. Let Red Packet align with them as well.

## Subtasks

- [ ] Locale keys normalization // @septs 
- [ ] `zh` translation // @neruthes 

## Notes

- None.
