### ISSUE TITLE
[Demand] A new UX "Manual" mode.

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#1552]
## Catalogue

- [x] UI/UX
- [x] Maskbook Core Feature
- [ ] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
    - /* List it here */

## Part 1: Introduction and Background

Today our application is based on finding and injecting DOM. That way is not stable and once it breaks, the user cannot use the application anymore.

## Part 2: Problem to Solve

Provide a new UX design that makes it possible to use Maskbook after the current (deep integration) way breaks.

## Part 3: Expected Behavior

The core rule:

> Do Not assume any knowledge on the DOM structure.

Based on the principle, I can imagine some designs in the UX mode.

1. Maskbook will not try to find a "natural" position to inject the entry of composition button. Instead, it displays a [FAB](https://material.io/components/buttons-floating-action-button) in the right bottom corner (so it does not need to have DOM knowledge).
2. Maskbook will not try to "auto paste" post payload for users. Instead, Maskbook will display an instruction to tell the user to "copy and paste" the content into the post dialog. This includes text and image payload.
3. Maskbook will not try to find posts for the user. Instead, Maskbook allows user to drag-and-drop the payload text or image on to the Maskbook button, and then to decrypt it.

## Notes

This is an Emergency braking feature to keep the lowest usability of Maskbook.

It's also useful when we need to support a brand-new social network. You don't need any hacks and DOM selectors; you just enable the manual mode.

**Comment by neruthes** [comment]
Good new work on the way :)

**Comment by zhouhanseng** [comment]
I like this idea.

**Comment by Jack-Works** [comment]
dont close

**Comment by Jack-Works** [comment]
close for housekeeping
