### ISSUE TITLE
[Demand] Added red packet history

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#1581]
## Catalogue

- [ ] UI/UX
- [ ] Maskbook Core Feature
- [x] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
    - /* List it here */

## Part 1: Introduction and Background
Our existing red packet history is kind of broken. If a transaction receipt is not received locally, it won't show up in our red packet history even though it is confirmed on the network.

## Part 2: Problem to Solve
Add a new way to query the history of the given address and the red packet contract to get both created and claimed red packets history.

## Part 3: Expected Behavior
- [x] Find the best option to query the contract (Etherscan, web3.js, etc)
- [x] Query the contract to get the red packet creation history of the given address
- [x] Query the contract to get the red packet claim history of the given address
- [ ] Upgrade the contract to make this query easier by providing an API
