### ISSUE TITLE
[Bounty] Online Event Registration Plugin

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#1892]
## Catalogue

- [ ] UI/UX
- [ ] Maskbook Core Feature
- [x] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other

## Part 1: Introduction and Background

Many events are relying on social networks to spread to and attract more users. However, Twitter does not support enclosing an event into a single post. All we can do is to share an eventbrite link in the tweet and let the others click on the links themselves. This is inefficient and we are aiming to solve this problem. 

## Part 2: Problem Description

We would like any participant to take a look at how Facebook event works, e.g. https://www.facebook.com/events/718053602385449. We are not expecting a complete replicate of a Facebook UI. We only require the following info:

1. Name
2. Location (could be a virtual event with an URL)
3. Description
4. Number of Attendees
5. Fee (could be 0; cryptocurrency payment is required, fiat is optional)
6. Attending Requirements (e.g. the account should have at least one transaction)
6. Registered Attendees (addresses and other info)

All registrations need to be logged on chain so you may want to write your own smart contract for this. 

## Notes

Feel free to @yisiliu if you have any questions.

**Comment by Tedko** [comment]
Maybe take a look of `kickback` ?

**Comment by Tedko** [comment]
https://kickback.events/
