### ISSUE TITLE
[Bug] New mobile app dashboard design & related modification

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#1896]
## Catalogue

- [x] UI/UX
- [ ] Maskbook Core Feature
- [ ] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
Our mobile app UX need refinement

## Part 2: Problem to Solve
1. A global entry for Mask Network dashboard page needed. Instead of an unstable injected one inside Twitter/Fb
2. A native navigation/menu bar at the top to indicators current webview location and provides quick action of navigation for users.
3. To be compatible with the new navigation/menu bar, the current mobile Mask Network dashboard menu bar needs re-design

## Part 3: Expected Behavior
- [x] Remove the injected entries of Mask Network dashboard from Twitter/Fb mobile web site as following:
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-10 at 15 17 27](https://user-images.githubusercontent.com/7972003/99016460-2455fc80-2592-11eb-84e4-c5a26aee11ef.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-10 at 15 18 25](https://user-images.githubusercontent.com/7972003/99016465-25872980-2592-11eb-8062-1d949ee86481.png)

- [x] Remove the link of CONNECTED persona, which means replace them with text labels without underline or touch event. **NOTE that do NOT modify UNCONNECTED and DISCONNECT BUTTON**
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-10 at 15 17 03](https://user-images.githubusercontent.com/7972003/99017421-d392d380-2592-11eb-8b92-b93e5ecbbed1.png)

- [x] Remove the menu bar on mobile. Use floating-action-buttons to replace current action buttons on the menu bar. Please use the current icon/color before the detailed design comes out.

- [ ] List all [(title) : (URL paths)] of dashboard in webshim-manifest.json for mobile apps to properly display dashboard related properties on the native navigation/menu bar. I will append details of this request later.

**Comment by jk234ert** [comment]
- [x] JS side modificaiton
- [x] iOS modification
- [ ] Android modification

**Comment by jk234ert** [comment]
Waiting for #1924 to finish
