### ISSUE TITLE
[Demand] Implementing Connective-based messaging interface for Android app

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#1941]
## Catalogue

- [x] UI/UX
- [] Maskbook Core Feature
- [ ] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
To implement the new Android app UX, Android app native needs a way to communicate with JS, since we are using GeckoView, the best (maybe only) solution is to use GeckoView's Connective-based messaging feature.

## Part 2: Problem to Solve
1. Android app native needs:
- A way to get some values from the JS side (Launch page setting & connected personas, etc..)
- To open Maskbook dashboard from the native side, the native needs to get the URL from JS by calling `browser.runtime.getURL()`, there is no direct interface in GeckoView to call a JS method.

## Part 3: Expected Behavior
As the GeckoView [documentation](https://firefox-source-docs.mozilla.org/mobile/android/geckoview/consumer/web-extensions.html#connection-based-messaging), this demand could be divided into following tasks:
- [ ] Add required permissions into the manifest.json (@jk234ert )
- [ ] Add `port.onMessage.addListener` in JS side, return results of :
    - [ ] Request of value of "Launch page setting" (Fb/Twitter/Dashboard)
    - [ ] Request of "Is there any connected personas"
    - [ ] Request of "Get the actual URL of `url`"
- [ ] Android native implement the new UX. (@jk234ert )

**Comment by Jack-Works** [comment]
@jk234ert We should use the native messaging as JSON RPC channel so it will be easier to extends two-way communication.

**Comment by Jack-Works** [comment]
If iOS and Android implements the same set of RPC methods, it is possible to abstract them better.

Today:

```ts
interface iOSHost {
    scanQRCode(): Promise<string>
    log(...args: any[]): Promise<void>
}
```

**Comment by jk234ert** [comment]
I'm afraid Android GeckoView does not support our RPC methods, need some investigation

**Comment by Jack-Works** [comment]
> I'm afraid Android GeckoView does not support our RPC methods, need some investigation

We just use the Connection-based port to transfer messages. It doesn't care about what is inside.

**Comment by jk234ert** [comment]
Detailed requirement:

- [ ] Following the official GeckoView [doc](https://firefox-source-docs.mozilla.org/mobile/android/geckoview/consumer/web-extensions.html#assets-messaging-background-js), add the following code scripts, ensure the code evaluated during Maskbook initialization, App native need to call send messages right after app finish launching to present proper UI to users:
```
// Establish connection with app
let port = browser.runtime.connectNative("browser");
port.onMessage.addListener(response => {
    // Implement as next request
});
port.postMessage("Hello from WebExtension!");
```

- [ ] Inside `port.onMessage.addListener`, check the received response from app native, then use `port.postMessage();` to send the requested values back to app native as following:

| Response Value                | The actual value app requests                                | postMessage example                                          |
| ----------------------------- | ------------------------------------------------------------ | ------------------------------------------------------------ |
| settings+launchPage           | The value stored in `browser.storage.get('settings+launchPage')` | Return the string value e.g. "facebook"                      |
| mobileIsMyPersonasInitialized | Check if there is any connected persona, if yes, return "true", otherwise return "false" | Return the string value, e.g. "true"                         |
| dashboadUrl                   | The value return by `browser.runtime.getURL('/index.html')`  | Return the string value, e.g. "moz-extension://xxxxxx-xxxx-xxx-xxx-xxx/index.html" |

**Comment by Jack-Works** [comment]
@jk234ert did you investigate my previous comment? We should use it has a low level messaging port.

**Comment by jk234ert** [comment]
> @jk234ert did you investigate my previous comment? We should use it has a low level messaging port.

Per as I know our current JSON RPC implementation on iOS is based on iOS's userContentController, a platform-specific interface similar to GeckoView's connect-based messaging. Refer to [GeckoView Doc](https://firefox-source-docs.mozilla.org/mobile/android/geckoview/consumer/web-extensions.html) 

Another difference is iOS WKWebview and Android AOSP WebView provide an `evaluateJavaScript` method to run arbitrary Javascript code in webview and get the eval result, which GeckoView does not provide.

>  a low level messaging port

The only way to build a messaging port in both platforms seems to be a mobile app host local server I guess?  If we aim to provide a unified interface, IMO we only need to define the same protocol (like the diagram I posted above), then write a different implementation for each platform.

**Comment by Jack-Works** [comment]
The channel is platform-specific it's true. But after we make the two-way connection we can run any protocol on it.

On iOS, webview is sending messages to native by `window.webkit.messageHandlers.*.postMessage`, native is receiving message by `WKUserContentController`. And native is sending messages by `evaluateJavaScript` and webview is receiving messages by `document.addEventListener`. The communication is established based on two simplex channels.

On Android `browser.runtime.connectNative` is a duplex channel so it will be easier to established the two-way connection.

`evaluateJavaScript` is only used to emulate/transfer the message from the native side which is not a necessary part of the two-way communication.

**Comment by jk234ert** [comment]
The way to establish a `two-way` connection is restricted by platforms. 
What we have a space to design are:
1. Should we wrap the connection method used on iOS and Android into a unified JS interface?
2. How we design the protocol/message, a simple string-type command like `getXXXValue` or a JSON-RPC message with a similar structure as the one being used on iOS.

The first question is not related to this issue.
For the 2nd question, a well structured JSON-RPC message is better for sure, but since we only have a few amounts of message types, I prefer a rough "command -> result" solution.

**Comment by Jack-Works** [comment]
> 1. Should we wrap the connection method used on iOS and Android into a unified JS interface?

Yes, when there are no platform-specific problems.

> How we design the protocol/message, a simple string-type command like getXXXValue or a JSON-RPC message with a similar structure as the one being used on iOS.

I strongly prefer the latter one, it's easier to extend in the future.

**Comment by jk234ert** [comment]
Implmentation continues in #1959

**Comment by jk234ert** [comment]
Channel implementation done
