### ISSUE TITLE
[Bounty] Extend Image Encryption in Twitter

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#1947]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [x] Mask Core Feature
  - [ ] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 500 DAI 

## Part 1: Problem Description
We would like to extend the image encryption functionality described in #1217 to Twitter so that users would also be able to tweet "encryption"(pixel-level shuffled) images. Some rebase job also needs to be done since our codebase has changed a lot since the previous bounty was finished in July.

## Part 2: Resources
You can refer to #1338 and #1352 on the implementation. https://www.youtube.com/watch?v=JzvILdOPN3A would also be helpful since our great community developer @nazariyv filmed a great video on how it works.

## Part 3: Contact and Support
@yisiliu for the mechanism
@guanbinrui for the implementation

**Comment by yisiliu** [comment]
@nazariyv are you interested in this?

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 500.0 DAI (500.0 USD @ $1.0/DAI)  attached to it as part of the DimensionDev fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://chat.gitcoin.co/'>Gitcoin Chat</a>
* $1,205,502.56 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by nazariyv** [comment]
@yisiliu absolutely! :+1:

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 12 months from now.
Please review their action plans below:


**1) [nazariyv](https://gitcoin.co/nazariyv) has been approved to start work.**

Hi there :) I will rebase the work I have done and extend it to Twitter

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097).

**Comment by yisiliu** [comment]
@nazariyv approved. Thanks for your contribution!

**Comment by gitcoinbot** [comment]
@nazariyv Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=100)

**Comment by nazariyv** [comment]
I am still working on this

**Comment by yisiliu** [comment]
@nazariyv How long do you think it'll take to finish the bounty? Just checking in

**Comment by gitcoinbot** [comment]
@nazariyv Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@nazariyv due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=100)

**Comment by yisiliu** [comment]
@nazariyv hey how's going? Can you update us your progress please?

**Comment by nazariyv** [comment]
hey, I will get a chance to get on this later this week / weekend. How urgent is this? @yisiliu

**Comment by yisiliu** [comment]
np @nazariyv take your time!

**Comment by nazariyv** [comment]
awesome, thank you! I remember about this :)

**Comment by gitcoinbot** [comment]
@nazariyv Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@nazariyv due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=100)

**Comment by Tedko** [comment]
hi @nazariyv happy holiday! just a friendly ping

**Comment by yisiliu** [comment]
@nazariyv hey man any update?

**Comment by nazariyv** [comment]
@yisiliu got swamped by a barrage of things guys. If you want to approve someone else for this, go ahead. Sorry about this.

**Comment by Tedko** [comment]
If you’re still available happy to let you finish this ;)

**Comment by nazariyv** [comment]
I will do my best :) I am juggling finishing off reNFT mainnet launch + something else that I will reveal eventually :)

**Comment by McCrearyD** [comment]
so, #1338 implemented the image encryption algorithm already and it was applied in the context of facebook already, right?

as i understand it, my job is now to simply use the algorithms and apply it to twitter. right?

**Comment by yisiliu** [comment]
> so, #1338 implemented the image encryption algorithm already and it was applied in the context of facebook already, right?
> 
> as i understand it, my job is now to simply use the algorithms and apply it to twitter. right?

yes that's correct. glhf

**Comment by McCrearyD** [comment]
:-)

**Comment by McCrearyD** [comment]
@yisiliu do you have a contributions doc? or somewhere documenting how to get set up with your environment? I understand it's a chrome extension built with react + npm, so I'm assuming just:

`npm i`
`npm start` -- build webpack
then go to chrome/brave + point to `dist`?

**Comment by yisiliu** [comment]
> @yisiliu do you have a contributions doc? or somewhere documenting how to get set up with your environment? I understand it's a chrome extension built with react + npm, so I'm assuming just:
> 
> `npm i`
> `npm start` -- build webpack
> then go to chrome/brave + point to `dist`?

please refer to https://github.com/DimensionDev/Maskbook/blob/master/docs/caveats.md

**Comment by McCrearyD** [comment]
should I start from the master branch or should I start from the WIP #1352?

**Comment by yisiliu** [comment]
That's actually a tradeoff but I guess starting from #1352 makes more sense. The problem is that you will need to rebase it to our latest master, which has changed a lot in the past few months. Your choice.

**Comment by McCrearyD** [comment]
when trying to set up my dev environment with hot reload, I'm having a lot of issues... i am running the required versions for pnpm & node, but I am getting this when I run `pnpm start`:

```
TypeError: Cannot read property 'toString' of undefined
    at /Users/dyllan/Code/Maskbook/node_modules/.pnpm/webpack@5.19.0_webpack-cli@4.4.0/node_modules/webpack/lib/cache/PackFileCacheStrategy.js:929:53
    at async Promise.all (index 6)
npm ERR! code 1
npm ERR! path /Users/dyllan/Code/Maskbook/packages/maskbook
npm ERR! command failed
npm ERR! command sh -c webpack "serve" "--mode" "development"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dyllan/.npm/_logs/2021-02-16T18_59_18_341Z-debug.log
```

the only way I can update the extension is if I keep rebuilding it manually.

**Comment by yisiliu** [comment]
@Jack-Works can you offer some help here?

**Comment by McCrearyD** [comment]
@yisiliu @Jack-Works nevermind! i got it, I just re-cloned and reran `pnpm i` now everything is working :-)

**Comment by McCrearyD** [comment]
although, could you point me in the direction for where the steganography output gets put into the post as an image? and also where it reads from this to decrypt it?

**Comment by McCrearyD** [comment]
@yisiliu progress update: basically finished, all I need to do is decrypt the image & use a random seed (right now I have a fixed one for testing).

is there a method for finding the image's bytes already in Maskbook? or will i have to figure that out myself?

![Screen Shot 2021-02-16 at 4 08 01 PM](https://user-images.githubusercontent.com/26421036/108137655-2dfb6e80-7071-11eb-9592-f003800e7887.png)

**Comment by Jack-Works** [comment]
> finding the image's bytes already in Maskbook

what is that mean?

**Comment by McCrearyD** [comment]
@Jack-Works in other words, i was asking if you had in place a way to grab the image element on the DOM & augment it’s data.

**Comment by yisiliu** [comment]
#2414 I am thinking if you can further hide the orignal photo once decrypted. What do you think? @McCrearyD

**Comment by McCrearyD** [comment]
@yisiliu i can do that. you want the encrypted image to be hidden by default but showable when you click a button? or should i just remove/replace the encrypted version altogether?

**Comment by yisiliu** [comment]
@McCrearyD I think ideally the former makes sense, e.g. {view original}

**Comment by McCrearyD** [comment]
right. also, did you also eventually want this functionality built into facebook in a future issue?

**Comment by yisiliu** [comment]
yup but we are not focusing on that right now. Once we are planning on that, or even other platforms like Minds.com or reddit, we will let you know! Thanks

**Comment by gitcoinbot** [comment]
@mccrearyd Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=100)

**Comment by McCrearyD** [comment]
yep, have only 1 change request to fulfill & it's almost complete. reorganized everything to me more react friendly & follow convention

**Comment by Jack-Works** [comment]
cool, please @ me when you're ready for review

**Comment by Tedko** [comment]
👍👍

**Comment by gitcoinbot** [comment]
@mccrearyd Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@mccrearyd due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=100)

**Comment by McCrearyD** [comment]
yes i'm here still, just started a new role though so getting settled in.

**Comment by gitcoinbot** [comment]
@mccrearyd Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=100)

**Comment by McCrearyD** [comment]
still here, haven't forgotten about it. waiting for a block of time to allocate for this

**Comment by McCrearyD** [comment]
is there a way you can snooze the reminder for like 10 days? sorry for taking so long, i didn't anticipate i would get hired before i finished this bounty.

**Comment by gitcoinbot** [comment]
@mccrearyd Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/1947/100024097?snooze=100)

**Comment by McCrearyD** [comment]
yes, i'm still here. i'm sorry this is taking so long, once again. :/

**Comment by McCrearyD** [comment]
update: i just fixed decryption & `DefaultTypedMessageImageRenderer` so i can resolve one of the review requests. i have to now fix the reveal button & then handle the refactor.

**Comment by Jack-Works** [comment]
it has been stale for years, close for housekeeping
