### ISSUE TITLE
[Demand] Use BEM method naming locale key?

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#1951]
## Catalogue

- [ ] UI/UX
- [ ] Maskbook Core Feature
- [ ] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [x] Other
  - Locale

## Part 1: Introduction and Background

Normalization locale key naming

## Notes

see http://getbem.com/introduction/

**Comment by septs** [comment]
CC @Jack-Works @guanbinrui @zhouhanseng any idea?

**Comment by Jack-Works** [comment]
No, we should use i18n namespace to separate them

**Comment by septs** [comment]
@Jack-Works start it (migrate to namespace)
