### ISSUE TITLE
[Demand] ITO Plugin

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#1968]
## Catalogue

- [ ] UI/UX
- [ ] Maskbook Core Feature
- [x] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
Implement ITO plugin

[Figma link](https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/Twitter?node-id=357%3A979)

## Part 2: Sub-tasks

- [ ] Integrate ITO contract ABI and implement corresponding data models
- [ ] Compose Dialog
    - [ ] Dialog UI
    - [ ] Dialog Behaviors
- [ ] ITO post decryption & interaction
    - [ ] ITO post decryption UI
    - [ ] ITO post interaction Dialog
- [ ] ITO notification snackbar
- [ ] ITO history in wallet
