### ISSUE TITLE
[Demand] Maskbook Multi-Chain Wallet Library

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Maskbook#1969]
## Catalogue

- [x] UI/UX
- [x] Maskbook Core Feature
- [ ] Maskbook Plugin Feature
- [x] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
We need a specific multi-chain support wallet library for Maskbook as the base component of all our block-chain cryptocurrency features.

**Comment by septs** [comment]
@Jack-Works split into `packages/plugin-wallet` for development? (try switch to monorepo?)
