### ISSUE TITLE
Mask ❤️ NFT [Bounty] Display NFTs natively on Maskbook

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2022]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [x] Beginner
  - [ ] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 1 weeks
- Bounty Size
  - [x] 500 DAI

## Part 1: Problem Description
After our presidential election NFT event(#1798), we decide to go deep in the NFT area by bringing "native" NFT support on Maskbook. The first step would be displaying all NFTs using Opensea-compatible metadata API on both Facebook and Twitter with Maskbook. The goal for this bounty is to detect any Opensea/Rarible/Superrare url and display the relevant NFT(s), e.g. collection https://opensea.io/collection/us-2020-election-nft or asset https://opensea.io/assets/0x797ce6d5a2e4ba7ed007b01a42f797a050a3cbd8/110278847780101343869399231375393952728601320591123168197704568786056038621800/. You will also need to do a little bit design job for this bounty. 

## Part 2: Resources
#1798 presidential election NFT
#1079 gitcoin plugin
https://docs.opensea.io/docs/2-adding-metadata Opensea Metadata API

## Part 3: Contact and Support
@yisiliu for design and algorithms
@guanbinrui for implementations

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 500.0 DAI (500.0 USD @ $1.0/DAI)  attached to it as part of the DimensionDev fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2022/100024357).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2022/100024357).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://chat.gitcoin.co/'>Gitcoin Chat</a>
* $1,269,347.49 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by jerrynoah96** [comment]
@yisiliu i am the person you responded to on the gitcoin chat some minutes ago, The codes are written majorly in typescript and i have no experience with that. How about i create kindof popup or a new Page in react displaying the NFTs perhaps upon clicks then we have it integrated in

**Comment by yisiliu** [comment]
@jerrynoah96 thanks but that's not ideal to us. What we want is a fully built-in feature like 
![image](https://user-images.githubusercontent.com/3343358/101142579-c2e4f300-3650-11eb-9e7d-e368e7de8055.png)

**Comment by jerrynoah96** [comment]
@yisiliu  Thanks

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 500.0 USDC (500.00 USD @ $1.0/USDC) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2022/100024359)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2022/100024359).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://chat.gitcoin.co/'>Gitcoin Chat</a>
* $1,284,183.65 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by brymut** [comment]
Hi @yisiliu, is this exclusively for the gr8 hackathon or is it open to anyone to try and solve?

**Comment by yisiliu** [comment]
@brymut it's open to be finished anytime as a long term project! Join us if you are interested

**Comment by brymut** [comment]
Hi again @yisiliu, would the detected Opensea/Rarible/Superrare url have to be a BarePost or a MaskedPost?

**Comment by Tedko** [comment]
For now it should work like this :

Alice sent nft url in original post;
Bob with Mask.Io will able to render  the election NFT like interface

**Comment by yisiliu** [comment]
@brymut it should detect a bare url just like our gitcoin grant plugin

**Comment by Tedko** [comment]
@brymut hey any updates?

**Comment by brymut** [comment]
Hey, nothing significant yet, was still learning about everything in this domain. However I have begun developing it, I should be able to get a PR open by tomorrow.

**Comment by Tedko** [comment]
> Hi @Tedko, nothing significant yet, was still learning about everything in this domain via the confluence page and the code. However I have begun developing it, I should be able to get a PR open by tomorrow. 

Great! Let us know if u need any help!

**Comment by Tedko** [comment]
hi @brymut any updt?

**Comment by sounak98** [comment]
@yisiliu I have started working on this, but I need some help with the documentation for dev env setup and adding new plugins using the plugin service.

**Comment by sounak98** [comment]
@yisiliu I have started working on this, but I need some help with the documentation for dev env setup and adding new plugins using the plugin service.

**Comment by Jack-Works** [comment]
hi, @sounak98 we need NPM@7 and Node 15. Did you try that?

**Comment by brymut** [comment]
Hi @Tedko . Sorry for the silence, got caught up with some personal stuff for the holiday. Almost done now.

**Comment by Tedko** [comment]
@brymut hi ! - @sounak98 is working on this as well. if you guys both work & finish this on same time we will merge the codebase of both & split the grant. cc @yisiliu ok?

**Comment by brymut** [comment]
Do you mean we collaborate? @Tedko

**Comment by brymut** [comment]
I don't mind

**Comment by Tedko** [comment]
@brymut yep! thoughts? @sounak98

**Comment by sounak98** [comment]
@Tedko @brymut as this is a relatively simple task, let's just do it on separate tracks, we can later merge the codebase if necessary.

**Comment by brymut** [comment]
Ok, I understand, we'll continue just as is then?

**Comment by Tedko** [comment]
Sure great!

**Comment by brymut** [comment]
I think I will stop work on this. I'd rather not do any double work. Thank you for the support @Tedko

**Comment by yisiliu** [comment]
> I think I will stop work on this. I'd rather not do any double work. Thank you for the support @Tedko

hey thanks for your input! If you are interested in our project, we can fund other issues for you to work on. Which part, in particular, are you interested? I can figure out something for you.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 1000.0 USDC (1000.00 USD @ $1.0/USDC) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2022/100024359)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2022/100024359).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://chat.gitcoin.co/'>Gitcoin Chat</a>
* $1,132,727.51 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by brymut** [comment]
Thank you @yisiliu. I'm particularly interested in UI/UX work on the front-end and I'd like to work on more documentation too.

**Comment by yisiliu** [comment]
@brymut sounds good! Allow us to think about it and I will get back to you later this week. Stay tuned!

**Comment by brymut** [comment]
Thank you!

**Comment by Jack-Works** [comment]
hi @brymut @sounak98 We've just updated the guide for developers. That will make the work easier! Please checkout this file
https://github.com/DimensionDev/Maskbook/blob/master/caveats.md

**Comment by Tedko** [comment]
@sounak98 the Gitcoin bounty is reopened . Can you check and apply and we can work on the merge on our side. Thx !!

**Comment by sounak98** [comment]
Hey @Tedko what do you mean by applying to the bounty? I had already applied before. This is the bounty right https://gitcoin.co/issue/DimensionDev/Maskbook/2022?

**Comment by Tedko** [comment]
Oh yeah. @sounak sorry my mistake

**Comment by brymut** [comment]
> @brymut sounds good! Allow us to think about it and I will get back to you later this week. Stay tuned!

Hi @yisiliu, sorry to bother, might you have an update on this?

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__The funding of 1000.0 USDC (1000.00 USD @ $1.0/USDC)  attached to this issue has been approved & issued to @sounak98.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2022/100024359)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,062,297.74 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__The funding of 1000.0 USDC (1000.00 USD @ $1.0/USDC)  attached to this issue has been approved & issued to @sounak98.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2022/100024359)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,061,297.74 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by septs** [comment]
@yisiliu reopen?

**Comment by Tedko** [comment]
Yisi will do a step 2 I guess. The step 1 is merged right?
