### ISSUE TITLE
[Bounty] Integrate Incognito as a plugin that enables private direct transfer

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2068]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 4 Weeks
- Bounty Size
  - [x] 1500 DAI <- increased from 1000 specifically for Gitcoin Hackathon Round 9

## Part 1: Problem Description
This bounty aims to integrate https://incognito.org/ as a plugin in Maskbook extension that users can shield and directly send ETH and other supported blockchains. We are looking for open ideas on the UI and how this plugin is invoked, e.g. when the mouse hovers on $PRV on Twitter, a popup window will show up with the pDex interface in it. Any idea is welcomed though.

This is a joint bounty with the Incognito team and official help from Incognito team will be offered.

## Part 2: Resources
https://we.incognito.org/t/prv-holders-presentation-november-2020/8135
https://ethresear.ch/t/incognito-mode-for-ethereum/6232
https://medium.com/incognito-chain/incognito-mode-for-ethereum-e0bbae096eaf
https://incscan.io/
http://docs.incognito.org/

## Part 3: Contact and Support
@yisiliu and @guanbinrui

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 1000.0 DAI (1000.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://chat.gitcoin.co/'>Gitcoin Chat</a>
* $1,203,744.07 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 10 months from now.
Please review their action plans below:


**1) [dasmygame](https://gitcoin.co/dasmygame) has been approved to start work.**

I have done very similar integration like this before, integrating goURL and WPSmartContracts into browser extensions and wordpress websites. I believe the same methodology can solve your problem.

1. There is currently an Incognito pApp (app integration for incognito) within their builder community called the Incognito Whale Bot, which reports noteworthy transactions within the Incognito chain, on twitter and telegram feeds. I would look a their source code and develop a clean low compute integration as a plugin for maskbook.

2. Design and develop a react app that will provide the specific functionality you guys want for each platform that maskbook connects to. From here its just platform dependent local development, for example twitter bootstrap pop-up window bot integration with incognito.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462).

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by sounak98** [comment]
@yisiliu @guanbinrui as far as I can see, the incognito transfers are only possible from a mobile device. Given this scenario, how will we use it to build a plugin on the web?

**Comment by yisiliu** [comment]
> @yisiliu @guanbinrui as far as I can see, the incognito transfers are only possible from a mobile device. Given this scenario, how will we use it to build a plugin on the web?

https://docs.incognito.org/developers-guide/quickstart/send-custom-privacy-token would this be helpful? @sounak98

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by sounak98** [comment]
@yisiliu for sending the token with incognito we would need to import the user's private keys, what's the plan for that?

**Comment by sounak98** [comment]
@Tedko @yisiliu @guanbinrui want to understand the exact requirements of this bounty, can you please help me understand what exactly we are looking to build?

**Comment by Tedko** [comment]
@ yisiliu <https://github.com/yisiliu> can you provide sounak more info ;)?

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by Tedko** [comment]
> @yisiliu for sending the token with incognito we would need to import the user's private keys, what's the plan for that? Do we plan to just create a wallet for the user on the fly and display a UI like this (this is the pDEX view from the iOS app).
> 
> 
> 
> ![IMG_D2079D75A2CD-1](https://user-images.githubusercontent.com/22390515/104552284-87c9dc80-565e-11eb-899e-82bb7a4e033d.jpeg)
> 
> 

For private key:

Actually our internal mask wallet do have wallet stored locally. Not sure which is the barrier here

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by Tedko** [comment]
@yisiliu @guanbinrui

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)

**Comment by gitcoinbot** [comment]
@dasmygame Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2068/100024462?snooze=100)
