### ISSUE TITLE
[Bounty] Adding Sia Network as another provider for the file service

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2069]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 4 weeks
- Bounty Size
  - [x] 1000 DAI

## Part 1: Problem Description
We have already integrated Arweave as the provider of our file service, by which users can upload any type of file and attach it to a social network post. To extend this capability and provide more options for our users, we would like to add more providers such as Sia. You might need to figure out how to create a micro-service to help pay for user's storage fees just like what we did with Arweave. Official help from Sia team can be directly linked in this bounty.

## Part 2: Resources
https://sia.tech/docs/

## Part 3: Contact and Support
@yisiliu and @septs

**Comment by septs** [comment]
@yisiliu need to explore remote signing solution?

**Comment by yisiliu** [comment]
> @yisiliu need to explore remote signing solution?

nope you just need to show up when developers have any questions about this issue

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 1000.0 DAI (1000.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://chat.gitcoin.co/'>Gitcoin Chat</a>
* $1,204,744.07 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by mul53** [comment]
hey @septs, i'm interested in this issue

**Comment by yisiliu** [comment]
@mul53 Hi! Do you want to test out our extension and see how file service works before starting the bounty? Thank you!

**Comment by mul53** [comment]
@yisiliu let me do that, let me take a look at the docs, thanks for the fast response

**Comment by developerfred** [comment]
@septs and @yisiliu, to encrypt attached we need a skykID, can we make everyone sign with a single skykeyID from the maskbook?

**Comment by Tedko** [comment]
> @septs and @yisiliu, to encrypt attached we need a skykID, can we make everyone sign with a single skykeyID from the maskbook?

hi @developerfred 
FYI. heres how we did for the AR integration:

https://arweave.net/vRJSopHVcFXwbhQVMaWBDm-UxBefN1BLoVsxXOQFWQU#xi4hApj0pTDKefNf

`#xi4hApj0pTDKefNf` is the AES key. 

if you open up https://arweave.net/vRJSopHVcFXwbhQVMaWBDm-UxBefN1BLoVsxXOQFWQU then you need to have the key.

For skynet/sia - whats ur proposal? we can do several iteration to achieve both decentralized and UX friendly -

**Comment by developerfred** [comment]
@Tedko In my code I made a new tab on the toggle placing two skynet and Arweave options. The users chooses in which service to host his file, but the skynet has N portals to host this file I randomly put it every time a user is going to upload, a portal and set it.

**Comment by Tedko** [comment]
@developerfred cool! Idk sia/sc 's token model. I assume (if I remember correctly) the file storage sometime is free? But need to pay sc later? (Asking so in case we need sc; we can prepare on our side and ping SC ppl)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 11 months from now.
Please review their action plans below:


**1) [developerfred](https://gitcoin.co/developerfred) has been approved to start work.**

I would love to work with that integration.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463).

**Comment by developerfred** [comment]
@Tedko can we do as Gitcoin does when claiming kudos? asking for some SIA for the fee?

**Comment by Tedko** [comment]
> @Tedko can we do as Gitcoin does when claiming kudos? asking for some SIA for the fee?

@developerfred im not sure on kudos. For SIA for free i guess definitely ok. I will ping SIA team.

**Comment by gitcoinbot** [comment]
@developerfred Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=100)

**Comment by gitcoinbot** [comment]
@developerfred Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@developerfred due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@developerfred due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2069/100024463?snooze=100)

**Comment by yisiliu** [comment]
will consider re-opening this in the future
