### ISSUE TITLE
[Demand] Enable Arweave bundled data standard in the file service

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2144]
## Catalogue

- [ ] UI/UX
- [ ] Maskbook Core Feature
- [x] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
Due to lack of an internal Arweave wallet, we decided to host a micro-service to sign the transaction for each user-uploaded file transactions. In this sense, users won't need to pay to upload files onto the Arweave network.

## Part 2: Problem to Solve
However, the problem resides in the data ownership. Now, the uploaded data belongs to a centralized address in our hosted remote-sign service. This needs to be solved to bring the ownership back to the users. This can be solved by https://github.com/ArweaveTeam/arweave-standards/blob/master/ans/ANS-102.md that allows delegation of payments without changing the data ownership. 

This also needs to be shipped along with our newly renovated internal wallet, which will likely come out in 3 months. By then, users would have been able to create their own Arweave wallet within this extension.

## Part 3: Expected Behavior
Users would still be able to upload files onto Arweave without paying for the transaction fees but they would be able to claim the ownership of the uploaded data.

## Notes
This is still just a draft and will be implemented in a low priority until the new internal wallet is implemented.

**Comment by Tedko** [comment]
Should we ping ARDrive folks as well?

**Comment by Tedko** [comment]
closed for now. in future will research bundler etc
