### ISSUE TITLE
[Bounty] Add CDN for the file service

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2160]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 500 DAI

## Part 1: Problem Description
Right now we are using Arweave as the "backend" of the file service, where users are able to upload files onto or download from. However, the endpoint is not stable as it might be influenced by a few factors. We would like to add a CDN to help improve this experience for our users all over the world.

In the future, we are planning to add more "backends"(#2069) and would appreciate the CDN as well.

## Part 2: Resources
https://github.com/DimensionDev/Maskbook/tree/master/packages/maskbook/src/plugins/FileService

## Part 3: Contact and Support
@yisiliu and @septs

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 500.0 DAI (500.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2160/100024558).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2160/100024558).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://chat.gitcoin.co/'>Gitcoin Chat</a>
* $1,000,195.82 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by haihongS** [comment]
🙋‍♂️🙋‍♂️🙋‍♂️

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 10 months from now.
Please review their action plans below:


**1) [haihongs](https://gitcoin.co/haihongs) has been approved to start work.**

- Test arweave api endpoint
- Communicate with Mask
- Add CDN service for Mask
- Test in different area
- Whooooa

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2160/100024558).

**Comment by yisiliu** [comment]
@haihongS please sync any update with us here, thanks

**Comment by haihongS** [comment]
Ok, let's start it.
=================

### The usual flow:
https://arweave.net/j8BNG1iTI0kebUQM9UlR9abW56fRmBZLnV3gsUOfo44

redirects to ->

https://r7ae2g2ysmrushtniqgpkskr6wtnnz5h2gmbms45lxqlcq47uoha.arweave.net/j8BNG1iTI0kebUQM9UlR9abW56fRmBZLnV3gsUOfo44

### CDN cache
We can offer a accelerate connection: https://coldcdn.com/api/cdn/bronil/j8BNG1iTI0kebUQM9UlR9abW56fRmBZLnV3gsUOfo44

When we check the content in HTML, found the _**real file link**_ in Arweave which needs to be changed in Mask.

<img src="https://user-images.githubusercontent.com/8394303/103401741-1af61300-4b85-11eb-95e7-005ca65c20ce.png" width="80%">

**Comment by yisiliu** [comment]
We'd like some speed tests from different areas. What's your thoughts? @septs

**Comment by haihongS** [comment]
Can we get much more information about the user location in using Mask & Arweave

**Comment by haihongS** [comment]
Can we get much more information about the user location in using Mask & Arweave

**Comment by yisiliu** [comment]
We do have some stats in Mask but you should probably test it all over the world to test out the robustness of your service

**Comment by haihongS** [comment]
> We do have some stats in Mask but you should probably test it all over the world to test out the robustness of your service

Yeah, so can we start with an alternative link which gives users an option to reach files through cache service, just like live streaming has multiple lines. 

e.g. users based in China Mainland and North America can try the alternative link, and we will check the status of service and do some tunings.

After several periods, we will know the performance and robustness of service, then comes the real CDN. 

@yisiliu

**Comment by yisiliu** [comment]
> Yeah, so can we start with an alternative link which gives users an option to reach files through cache service, just like live streaming has multiple lines.
> 

I guess the ideal solution would require you to modify our code so that it'll test out all the options and choose the best available.

**Comment by haihongS** [comment]
sure, let me check the code

**Comment by gitcoinbot** [comment]
@haihongs Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2160/100024558?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2160/100024558?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2160/100024558?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2160/100024558?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2160/100024558?snooze=100)

**Comment by haihongS** [comment]
yeah, wip right now

**Comment by haihongS** [comment]
`export const signing = 'https://service.maskbook.com/arweave-remote-signing'`

Does Mask maintain the signing system in private and keep SK?

**Comment by yisiliu** [comment]
@septs

**Comment by septs** [comment]
> `export const signing = 'https://service.maskbook.com/arweave-remote-signing'`
> 
> Does Mask maintain the signing system in private and keep SK?

as arweave does not provide remote signing method,
but this repo include some non public limit settings, not can fully open source.
(if you idea access this codebase, need to get @yisiliu approve)

it's core logic like:

```ts
  const [data, parsed] = await readRequest(ctx.req.read());
  const signed = await instance.crypto.sign(keyfile, data);
  const id = await instance.crypto.hash(signed);
  ctx.body = {
    signature: bufferTob64Url(signed),
    id: bufferTob64Url(id),
  };
```

wrote here response body to `transaction.setSignature`, signed by remote

https://github.com/DimensionDev/Maskbook/blob/75de7fe06a98dd5c1d5289053bb5dcc55d771546/packages/maskbook/src/plugins/FileService/arweave/remote-signing.ts#L6-L13

**Comment by septs** [comment]
@yisiliu approved
@haihongS plz send a email to `septs@dimension.im` request the codebase, thanks

**Comment by haihongS** [comment]
> @haihongS plz send a email to `septs@dimension.im` request the codebase, thanks on @yisiliu approved

Thx, and I can continue the idea without this part right now.

-----

I read some codes and tried file service in twitter, here is my understanding of process:

User A clicks the FileService plugin in twitter and drops a file into it

-> mask builds an arweave `transaction` 
-> signed by mask's `signing system` 
-> `broadcast` to arweave network through endpoint:arweave.net
-> waiting for the `confirmation` of arweave network

-> display arweave link: `https://arweave.net/MASK_FILE_HASH#KEY`
-> arweave redirect: `https://balabala.arweave.net/MASK_FILE_HASH#KEY`
-> request real file download link: `https://arweave.net/REAL_FILE_HASH`

plz point out the mistakes above if it has  @septs

**Comment by haihongS** [comment]
Besides, I noticed the lack of the whole encryption, which means, I can scan the history of transactions in mask's account and find the real file hash without the key.

Two sequent transactions, one for key check and the other represents the real file.

**Comment by septs** [comment]
> Besides, I noticed the lack of the whole encryption, which means, I can scan the history of transactions in mask's account and find the real file hash without the key.

key using hmac-sha256 verify user key correctness.

see https://github.com/DimensionDev/Maskbook-FileService-LandingPage/blob/1d87424b21ad3815e4987cd9c2e7bee2ec176112/src/components/Password.tsx#L77-L83

> Two sequent transactions, one for key check and the other represents the real file.

1. first transaction
   1. generate (un)encrypted file with metadata <sup>1</sup>
   2. upload to arwavae
2. two transaction
    1. inject metadata (include real file `link`, `filename`, etc) <sup>2</sup> into **Landing page** <sup>3</sup>  
    2. upload to arwavae

-----------------------------

notes:

1. https://github.com/DimensionDev/common-protocols/blob/master/specs/0-BSFOW.md
2. https://github.com/DimensionDev/Maskbook/blob/75de7fe06a98dd5c1d5289053bb5dcc55d771546/packages/maskbook/src/plugins/FileService/arweave/index.ts#L52-L67
3. https://github.com/DimensionDev/Maskbook-FileService-LandingPage
    https://en.wikipedia.org/wiki/Landing_page

**Comment by haihongS** [comment]
awesome codes, and now we need to talk about the solution for this issue.

### purpose
- offer a cdn for file service at that moment
- acceleration other components for mask in later

### concern
the robustness of service

### solution
**keep the original arweave link, but give users an alternative link**

I have noticed the two key point links in file service, one is `landingTxID` and the other is `payloadTxID`

so, I need to add alter link in `Maskbook-FileService-LandingPage`. Cuz every encoding in file service will fetch data from  `landing page`, hot-update will be much easy.

Then, we can offer the entry atler landing-page link in twitter, which will help users who can't reach arweave endpoint.

@septs how's your idea?

**Comment by haihongS** [comment]
we have add a 10MB test file in 
https://arweave.net/MQvwlLNyJcE5-A7wo6oUE0j4QwlXfXxYNbSlwR70ZAg#FkNfuQppBpeyGs7N

also cache link for `landingPage` 
https://coldcdn.com/api/cdn/bronil/MQvwlLNyJcE5-A7wo6oUE0j4QwlXfXxYNbSlwR70ZAg#FkNfuQppBpeyGs7N

plz check the speed.

**Comment by haihongS** [comment]
In chrome incognito mode, I tested two files.

one is from original arweave endpoint(8.7M):
https://arweave.net/9JgBCn8uaToqiTbugQ43yRuQioLbvbeTA5mSLEbnYt8#sample

another is the cached one(9.4M):
https://arweave.net/VzLiXPYJLyAmWoQbH05W5P5SOaqWesQCFg7a935iKYE#MrRBRMeAnB8EQBE4

The results is much ideal.

![image](https://user-images.githubusercontent.com/8394303/104415236-9a83d900-55ac-11eb-9349-c6e3a78e4903.png)

![image](https://user-images.githubusercontent.com/8394303/104415249-a4a5d780-55ac-11eb-89b5-dbfa83243033.png)

----
The strategy keeps the same as traditional cloud service provider. When the first request arrived, the system will redirect to origin source and schedule a job, which can cache file to the user's neighbourhood. As soon as the caching ready, new request will be distributed to cached nodes according to load-balance strategy.

**Comment by haihongS** [comment]
Hope it will be convenient to uses and save the cost of mask. ^...^

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work for 500.0 DAI (500.0 USD @ $1.0/DAI) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2160/100024558)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2160/100024558).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,001,251.69 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by Tedko** [comment]
consider done @yisiliu

**Comment by Tedko** [comment]
should close gitcoin bounty if this is consider done @yisiliu
