### ISSUE TITLE
[Bounty] Replace Twitter Profile Header Photo with any media type

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2236]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 Weeks
- Bounty Size
  - [x] 2000 USD <- increased from 1000 specifically for the Gitcoin Hackathon Round 9

## Part 1: Problem Description

Inspired by Twitter user [@Prathkum](https://twitter.com/Prathkum/status/1345041164605513728), I think it's worth adding something similar to our Maskbook users by enabling decorating your Twitter header with any media type, e.g., a gif, a video or even an html5 page. We would like you to explore a possible solution yourself, although I do have an idea in my mind. Please propose your idea here and I will share my thoughts with you in the end. 

## Part 2: Resources

https://github.com/DimensionDev/Holoflows-Kit 
https://github.com/DimensionDev/Maskbook/tree/master/packages/maskbook/src/plugins
https://github.com/DimensionDev/Stego-JS

## Part 3: Contact and Support

Join our discord server at https://discord.gg/jFGxvCHr
and @yisiliu @guanbinrui here

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 1000.0 DAI (1000.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $993,606.09 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 10 months from now.
Please review their action plans below:


**1) [thehated1](https://gitcoin.co/thehated1) has been approved to start work.**

By adding something similar to our Maskbook users by enabling decorating my Twitter header.
@afronomad_

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589).

**Comment by yisiliu** [comment]
hi @thehated1 welcome! Can you please do some research on our project and reply here with your proposal? Thank you! You can always ask us questions or join our [discord server](https://discord.gg/jFGxvCHr) for a faster reply:)

**Comment by echinocacti** [comment]
I'm interested in this bounty.

I have a lot of experience in node/frontend development, typescript and computer graphics (Canvas + webgl and VR); less in web3 dev.

I would like to discuss about this bounty if possibile.

**Comment by yisiliu** [comment]
@echinocacti awesome! Let's schedule a meeting to discuss this bounty! Book me a meeting at: https://calendly.com/yisiliu. To work on this issue, you don't need any web3 dev so you are totally fine. Let's brainstorm and see what we can create.

**Comment by brymut** [comment]
Hi, @yisiliu is this offer to schedule a meeting with you open to anyone or do we apply using gitcoin first?

**Comment by gitcoinbot** [comment]
@thehated1 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=100)

**Comment by TheHated1** [comment]
I'm still work on it:
https://github.com/TheHated1/TwitterHeader

**Comment by yisiliu** [comment]
> Hi, @yisiliu is this offer to schedule a meeting with you open to anyone or do we apply using gitcoin first?

Please schedule a meeting with me first. I can probably offer you something else to work on.

**Comment by yisiliu** [comment]
> I'm still work on it:
> https://github.com/TheHated1/TwitterHeader

As mentioned, I would need to talk to all the participants first to make sure they know how this bounty works and what I really needed. I have already talked to @echinocacti and I want to talk to you too if you want to finish our bounty. Thank you.

**Comment by brymut** [comment]
> 
> Please schedule a meeting with me first. I can probably offer you something else to work on.

Yes please, could I please get something else to work on if you feel like this is already covered?

**Comment by yisiliu** [comment]
> 
> > 
> > Please schedule a meeting with me first. I can probably offer you something else to work on.
> 
> Yes please, could I please get something else to work on if you feel like this is already covered? @yisiliu but if not, I'll schedule a meeting today
> 
> 

This is what I am planning to do today: to add something else to our issue list

**Comment by brymut** [comment]
> > 
> > > 
> > > Please schedule a meeting with me first. I can probably offer you something else to work on.
> > 
> > Yes please, could I please get something else to work on if you feel like this is already covered? @yisiliu but if not, I'll schedule a meeting today
> > 
> > 
> 
> This is what I am planning to do today: to add something else to our issue list

Ok great, thank you.

**Comment by gitcoinbot** [comment]
@thehated1 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=100)

**Comment by TheHated1** [comment]
IN process..

**Comment by gitcoinbot** [comment]
@thehated1 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@thehated1 due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589?snooze=100)

**Comment by TheHated1** [comment]
[TwitterProfile](https://twitter.com/afronomad_)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work for 1000.0 DAI (1000.0 USD @ $1.0/DAI) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,057,460.77 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by ManyRios** [comment]
Working on this!

**Comment by ManyRios** [comment]
This bounty is still open?

**Comment by yisiliu** [comment]
@ManyRios actually.....yes!

**Comment by ManyRios** [comment]
![image](https://user-images.githubusercontent.com/34518489/108872649-c1342700-75d0-11eb-9ebc-bc632b1e9918.png)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 8 months from now.
Please review their action plans below:


**1) [az111z](https://gitcoin.co/az111z) has started work.**

We are an ambitious team and we hope for success, so we can move forward and we have been granted the grant of support for us, and we will be, according to your story

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 2000.0 DAI (2000.00 USD @ $1.0/DAI) has been submitted by__:

 1. [@thehated1](https://gitcoin.co/thehated1)



@yisiliu please take a look at the submitted work:
* [PR](https://github.com/DimensionDev/Maskbook/issues/2236) by @thehated1

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2236/100024589).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,465,380.62 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by spiritbro1** [comment]
![image](https://user-images.githubusercontent.com/62529025/111232524-d7f0fb00-861d-11eb-942e-a6e29cf671ca.png)

hello the discord server is invalid, also want to ask, because the problem is changing the header of the twitter, that means that it only work for browser extension of this mask right? because the mobile version can't change the twitter header as far as i know, if the mobile version can and if you have some directions that i can go to learn please tell me i will definitely take a look at that

**Comment by yisiliu** [comment]
@spiritbro1 hey man please join with this [link](https://discord.gg/4Xccj7a75Q). For now, I only want you to explore the possibility within the browser extension scope. We do have mobile apps on both iOS and Android but let's just focus on the browser first. Thanks!

**Comment by spiritbro1** [comment]
> @spiritbro1 hey man please join with this [link](https://discord.gg/4Xccj7a75Q). For now, I only want you to explore the possibility within the browser extension scope. We do have mobile apps on both iOS and Android but let's just focus on the browser first. Thanks!

@yisiliu wow thank you for the reply i will try to implement that on browser extension then, and want to ask again in discord theres so many channel where should i ask for this particular issue?

**Comment by yisiliu** [comment]
@spiritbro1 haha right that was annoying. Please find me in #bounties lol

**Comment by Jack-Works** [comment]
it has been stale for a while, close for housekeeping
