### ISSUE TITLE
[Bounty] Bluesky <Ecosystem Review> Translation

### ISSUE THREAD

**Issue by Miaommmisokay** [DimensionDev/Maskbook#2296]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [x] Beginner
  - [ ] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [ ] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [x] Other
    - [x] Translation
- Time Commitment
  - [x] 15 Days
- Bounty Size
  - [x] 500 Dai

## Part 1: Problem Description
Twitter CEO Jack Dorsey has announced a new research team called Bluesky on December 11, 2019, which was an initiative to develop an open and decentralized standard for social media. On January 22, Bluesky released a 61-page <Ecosystem Review>. The Review was an overview of the most viable decentralized social network protocols and apps. 

With the sponsor of Mask Network, Fat Garage will launch the first bounty: Translating the Bluesky’s <Ecosystem Review> into Mandarin.

The whole translation will be processed on the Roamsearch.

## Part 2: Resources
Ecosystem Review
https://coywolf.media/file/coywolf/pdf/decentralized-social-ecosystem-review.pdf
Roam for micro-tasking — make 1st digital $ together
https://roamresearch.com/#/app/fat-garage/page/VvOZ0xzzF

## Part 3: Contact and Support
E-mail: info@fat-garage.com

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 500.0 DAI (500.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,041,755.81 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 9 months from now.
Please review their action plans below:


**1) [erich0123](https://gitcoin.co/erich0123) has been approved to start work.**

Hello, I am interested in translating the paper. I do not speak Mandarin unfortunately but I am a native German speaker and could translate it into German if you wish.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668).

**Comment by gitcoinbot** [comment]
@erich0123 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668?snooze=100)

**Comment by erich0123** [comment]
Hello, I've submitted the translated ActivitySub section as a WIP on gitcoin.co, but maybe you didn't get notified. Here it is again: https://gist.github.com/erich0123/6e2b5d5e812dca51b2dd983ed1f03203

**Comment by linluz** [comment]
Hello, I tried to send an email to info@fat-garage.com to get the trial translation text, but there was no response! Can you tell me what to do ? Learning the behavior of the above brothers, can I directly translate a paragraph into Chinese?

**Comment by yisiliu** [comment]
> Hello, I've submitted the translated ActivitySub section as a WIP on gitcoin.co, but maybe you didn't get notified. Here it is again: https://gist.github.com/erich0123/6e2b5d5e812dca51b2dd983ed1f03203

Sorry I didn't get the notice on gitcoin. I will let you know soon and will probably open a new issue for you as a separate bounty.

**Comment by yisiliu** [comment]
> Hello, I tried to send an email to info@fat-garage.com to get the trial translation text, but there was no response! Can you tell me what to do ? Learning the behavior of the above brothers, can I directly translate a paragraph into Chinese?

Hi welcome! We will let them know and respond to your email soon. In the mean time, a trial translation of a few paragraphs would be definitely helpful.

**Comment by gitcoinbot** [comment]
@erich0123 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@erich0123 due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2296/100024668?snooze=100)
