### ISSUE TITLE
[Bounty] Bluesky in more language 

### ISSUE THREAD

**Issue by tungnguyenvt** [DimensionDev/Maskbook#2297]
## Catalogue

- Platform
  - [ x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [x ] Beginner
  - [ ] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [ ] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [x ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x]  15 days
- Bounty Size
  - [x] 500 dai

## Part 1: Problem Description
Twitter CEO Jack Dorsey has announced a new research team called Bluesky on December 11, 2019, which was an initiative to develop an open and decentralized standard for social media. On January 22, Bluesky released a 61-page . The Review was an overview of the most viable decentralized social network protocols and apps.

With the sponsor of Mask Network, Fat Garage will launch the first bounty: Translating the Bluesky’s into Mandarin.

The whole translation will be processed on the Roamsearch.
## Part 2: Resources
Ecosystem Review https://coywolf.media/file/coywolf/pdf/decentralized-social-ecosystem-review.pdf Roam for micro-tasking — make 1st digital $ together https://roamresearch.com/#/app/fat-garage/page/VvOZ0xzzF
## Part 3: Contact and Support
E-mail: info@fat-garage.com

**Comment by septs** [comment]
CC @yisiliu @Tedko

**Comment by Tedko** [comment]
Yeah we’re happy to sponsor

**Comment by tungnguyenvt** [comment]
yes i like it

**Comment by Jack-Works** [comment]
please give this issue a title thanks

**Comment by Tedko** [comment]
duplicate w/ https://github.com/DimensionDev/Maskbook/issues/2296 ? @tungnguyenvt

**Comment by linluz** [comment]
@tungnguyenvt 我发了邮件了，但是那个邮箱没回复我 怎么办呢？没有试翻译文本的话，我直接学习那位德国人民，把第一篇翻译了？

**Comment by Tedko** [comment]
> @tungnguyenvt 我发了邮件了，但是那个邮箱没回复我 怎么办呢？没有试翻译文本的话，我直接学习那位德国人民，把第一篇翻译了？

@yisiliu cc
