### ISSUE TITLE
[Bounty] Add SashimiSwap

### ISSUE THREAD

**Issue by jason-hoopox** [DimensionDev/Maskbook#2300]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 Weeks
- Bounty Size
  - [x] 500 USDT

## Part 1: Problem Description
Add SashimiSwap as a trading provider of the Trade plugin. 

## Part 2: Resources
The SashimiSwap project is a clone of Uniswap.
- thegraph link:
https://api.thegraph.com/subgraphs/name/sashimiproject/sashimi
- contract address：
sashimi router: 
0x31db862df7be09718a860c46ab17ca57966e69ed
sashimi factory:
0xf028f723ed1d0fe01cc59973c49298aa95c57472
- SDK(npm)
@sashimiswap/sdk@1.0.3

## Part 3: Contact and Support
E-mail: developer@aelf.io

**Comment by guanbinrui** [comment]
It will be easy to integrate cause we have built SushiSwap into the trader plugin a few weeks ago.

Learn more: #2256

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 500.0 USDT (500.0 USD @ $1.0/USDT)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2300/100024671).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2300/100024671).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,036,030.71 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by jason-aelf** [comment]
hi @KiChjang welcome! Could you reply here with your proposal? Thank you! You can always ask us questions or send it to the E-mail "developer@sashimi.cool".

**Comment by KiChjang** [comment]
@jason-hoopox I haven't been accepted, but it looks like gitcoin's integration bot is down, so I'll just rewrite what I have on the gitcoin bounty page:

"Will reuse the Sushiswap integration as a template for Sashimiswap for development. Also reuse the helper classes from the Sushiswap integration as necessary. "

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 9 months from now.
Please review their action plans below:


**1) [kichjang](https://gitcoin.co/kichjang) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2300/100024671?mutate_worker_action=approve&worker=kichjang) | [reject worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2300/100024671?mutate_worker_action=reject&worker=kichjang))_.**

Will reuse the Sushiswap integration as a template for Sashimiswap for development. Also reuse the helper classes from the Sushiswap integration as necessary.
**2) [hhio618](https://gitcoin.co/hhio618) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2300/100024671?mutate_worker_action=approve&worker=hhio618) | [reject worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2300/100024671?mutate_worker_action=reject&worker=hhio618))_.**

Already have experiences with Uniswap protocol and its smart contracts.
**3) [developerfred](https://gitcoin.co/developerfred) has been approved to start work.**

I used the pull request for sushiswap integration to do sashimiswap integration.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2300/100024671).

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work for 500.0 USDT (500.00 USD @ $1.0/USDT) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2300/100024671)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2300/100024671).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,060,889.29 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by developerfred** [comment]
Hi @jason-hoopox, any update?

**Comment by jason-hoopox** [comment]
@developerfred It's ok. I have paid.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__The funding of 500.0 USDT (500.0 USD @ $1.0/USDT)  attached to this issue has been approved & issued to @developerfred.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2300/100024671)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,047,034.58 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
