### ISSUE TITLE
[Bounty] Integrate Mask in Minds.com

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2323]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [ ] Intermediate
  - [x] Advanced
- Category
  - [x] Mask Core Feature
  - [ ] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 1 month
- Bounty Size
  - [x] 2500 USD

## Part 1: Problem Description
Minds is an alt-tech blockchain-based social network. Users can earn money or cryptocurrency for using Minds, and tokens can be used to boost their posts or crowdfund other users. Minds has been described as more privacy-focused than mainstream social media networks. (source: Wikipedia)

We are co-operating with Minds and our goal is to integrate the entire function into Minds so that the existing Minds users can use have the same functionality and interface as we have in Twitter and Facebook, including the encryption & decryption and the plugin execution environment.

We are expecting developers to have a strong knowledge in what Mask can do so please do research before applying. Thank you.

## Part 2: Resources
https://www.minds.com/
https://developers.minds.com 
https://mask.io

Or ask questions on telegram @ here w/ both teams: 
https://t.me/joinchat/HR15dCCrVzyKjrul

## Part 3: Contact and Support
@yisiliu @Jack-Works

**Comment by Jack-Works** [comment]
So this looks familiar. I have a list of questions.

- Is it a decentralized network like the matrix?
- Do their users need to install Maskbook to use this feature?
- Co-operative with FB/Twitter?

**Comment by yisiliu** [comment]
> So this looks familiar. I have a list of questions.
> 
> * Is it a decentralized network like the matrix?
nope their username looks like this https://www.minds.com/yisiliu/
> * Do their users need to install Maskbook to use this feature?
yes for sure
> * Co-operative with FB/Twitter?
yes

**Comment by Jack-Works** [comment]
oh so will they provide a stable interface for us to inject or we have to do the same thing as what we do to FB?

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 2500.0 DAI (2500.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,056,948.39 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by yisiliu** [comment]
> oh so will they provide a stable interface for us to inject or we have to do the same thing as what we do to FB?

It's all gonna be community work!

**Comment by CoeJoder** [comment]
Please consider increasing the bounty, it's quite a bit of work.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 9 months from now.
Please review their action plans below:


**1) [mccrearyd](https://gitcoin.co/mccrearyd) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?mutate_worker_action=approve&worker=mccrearyd) | [reject worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?mutate_worker_action=reject&worker=mccrearyd))_.**

- i have worked for you before on another bounty, so i’ve already familiarized myself with the inner workings.

- do you mean, you want to add support for minds within Maskbook? or the other way around? sorry, i couldn’t understand the write up.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 8 months from now.
Please review their action plans below:


**1) [sevak-crypto](https://gitcoin.co/sevak-crypto) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?mutate_worker_action=approve&worker=sevak-crypto) | [reject worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?mutate_worker_action=reject&worker=sevak-crypto))_.**

I will attempt this and hopefully complete it.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 7 months from now.
Please review their action plans below:


**1) [jimist](https://gitcoin.co/jimist) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?mutate_worker_action=approve&worker=jimist) | [reject worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?mutate_worker_action=reject&worker=jimist))_.**

As I understand the encryption and decryption must happen on the client-side, any reference on the encryption document; I'm alright on the minds' code with a hint on mask.io about encryption I'm ready to get it done.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698).

**Comment by gitcoinbot** [comment]
@jimist Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 6 months from now.
Please review their action plans below:


**1) [manishoo](https://gitcoin.co/manishoo) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?mutate_worker_action=approve&worker=manishoo) | [reject worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?mutate_worker_action=reject&worker=manishoo))_.**

Hey! My PR is awaiting the final review here: https://github.com/DimensionDev/Maskbook/pull/2990

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698).

**Comment by gitcoinbot** [comment]
@manishoo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=100)

**Comment by manishoo** [comment]
Yes @gitcoinbot, I'm closely following the [Token Hashtags issue on Minds](https://gitlab.com/minds/engine/-/issues/1920) so that we can have trending info on $coin hover and in search result.

I'm also waiting for feedback from @Jack-Works regarding the paste functionality of Image Payload which I described [here](https://github.com/DimensionDev/Maskbook/pull/2990#issuecomment-830072726):

> Image payload does not seem to work because the current implementation proxies the addEventListener of the page and uses it to send Clipboard paste events without getting a "clipboardRead" permission for the extension.

> Although this works fine with Twitter and Facebook, it does not seem to work with Minds. I suspect the reason is because Minds is using Angular and that Angular doesn't seem to use the "addEventListener" method that we are proxying. (The exact line of the problem is [here](https://github.com/DimensionDev/Maskbook/blob/e33505ad6aaefe34f717685c8bf48bbf80760330/packages/maskbook/src/extension/injected-script/addEventListener.ts#L53))

> The only other implementation that I could get to work is to add the "clipboardRead" permission, write the image to clipboard, and paste it to the textarea. Which is not ideal because it adds an extra permission to the extension.

I might be missing something regarding the Image Payload issue. But I've confirmed that there is no event listener for the paste event in [CapturedListeners](https://github.com/DimensionDev/Maskbook/blob/0c40d893349dff2792a297ed7131c96885d338e4/packages/maskbook/src/extension/injected-script/addEventListener.ts#L53)

And I'm also waiting for a response from @yisiliu or @AinuX regarding how I can get some Ropsten $Mask token to test ITO. Or if that isn't necessary, how can I test ITO?

**Comment by Tedko** [comment]
Hi there. you wanna try test Ito on minds.com ?;)?

**Comment by manishoo** [comment]
Yes @Tedko!

**Comment by Jack-Works** [comment]
> I suspect the reason is because Minds is using Angular and that Angular doesn't seem to use the "addEventListener" method that we are proxying.

Yes, our current solution is for React-based applications. Is it possible to require `clipboard write` permission on demand?

**Comment by manishoo** [comment]
> Yes, our current solution is for React-based applications. Is it possible to require `clipboard write` permission on demand?

It seems to be possible. I'm investigating it

**Comment by gitcoinbot** [comment]
@manishoo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=100)

**Comment by gitcoinbot** [comment]
@manishoo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=100)

**Comment by manishoo** [comment]
I'm waiting for further review and test

**Comment by gitcoinbot** [comment]
@manishoo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2323/100024698?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__The funding of 2500.0 DAI (2500.00 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @manishoo.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/2323/100024698)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,294,106.74 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__The funding of 2500.0 DAI (2500.00 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @manishoo.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/2323/100024698)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,294,106.74 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__The funding of 2500.0 DAI (2500.00 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @manishoo.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/2323/100024698)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,294,106.74 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__The funding of 2500.0 DAI (2500.00 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @manishoo.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/2323/100024698)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,294,106.74 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__The funding of 2500.0 DAI (2500.00 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @manishoo.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/2323/100024698)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,294,106.74 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__The funding of 2500.0 DAI (2500.00 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @manishoo.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/2323/100024698)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,294,106.74 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__The funding of 2500.0 DAI (2500.00 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @manishoo.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/2323/100024698)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,294,106.74 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__The funding of 2500.0 DAI (2500.00 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @manishoo.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/2323/100024698)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,294,106.74 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
