### ISSUE TITLE
[Bounty] Enhance the file service with ArDrive.io

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2362]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 4 weeks
- Bounty Size
  - [x] 2000 USD

## Part 1: Problem Description

ArDrive is a suite of file sync apps that let users pay once to store their data forever on Arweave.  Our web and desktop apps focus on the core features of file sync like uploading and downloading, while giving the best security for private files and integrating with Arweave wallets for payments.

Mask Network is a browser extension that allows users to create encrypted posts and choose who is able to decrypt. Built upon this access control system and the capability of injecting any DOM elements into any social media, Mask Network creates an open market that welcomes everyone to create their own Dapplet or plugin on their favorite platforms.

We need help bringing the gap between Web2 apps and ArDrive.  ArDrive-Connect gives other web applications a standard set of libraries and interfaces that lets them connect their app and users into the ArDrive.  Applications that connect with ArDrive can give their users the ability to upload, download and share their files from the PermaWeb.  We have partnered with Mask Network to deliver this capability in their social network applications, so their users can easily leverage the PermaWeb for file sharing.

The detailed description including the user stories can be found [here](https://drive.google.com/file/d/1SXZfvWnIiXQZw5HsjNOO62UMaIVawQ3Q/view?usp=sharing).

## Part 2: Resources

https://ardrive.io

https://github.com/ardriveapp

https://github.com/DimensionDev/Maskbook 

https://github.com/ardriveapp/docs/blob/main/ArweaveFileSystem.md 

## Part 3: Contact and Support

[ArDrive Discord Server](https://discord.gg/ya4hf2H)

[Mask Discord Server](https://discord.gg/4Xccj7a75Q)

phil@ardrive.io

@yisiliu @septs

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 2000.0 DAI (2000.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,058,948.39 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 9 months from now.
Please review their action plans below:


**1) [brymut](https://gitcoin.co/brymut) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?mutate_worker_action=approve&worker=brymut) | [reject worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?mutate_worker_action=reject&worker=brymut))_.**

As a frontend developer, and familiarity with the mask project I can help with updating the File Service with ArDrive and work with the project maintainers for feedback to work out the best solution.
**2) [jay-dee7](https://gitcoin.co/jay-dee7) has been approved to start work.**

Hey yisiliu,
This bounty sounds very cool.
I've been contributing to ipfs and similar projects for a while and I'm familiar with arweave and browser extension/plugin development. I'd really love to work on this one :)

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699).

**Comment by jay-dee7** [comment]
hey @yisiliu thanks a lot for approving me.
I'll do my project setup and try to hit a trial run and share any questions/concerns if I have any. I usually do most of my work over the weekends but I'll share something before that :)

**Comment by yisiliu** [comment]
> hey @yisiliu thanks a lot for approving me.
> I'll do my project setup and try to hit a trial run and share any questions/concerns if I have any. I usually do most of my work over the weekends but I'll share something before that :)

Yes please!!! You can schedule a meeting with me at: https://calendly.com/yisiliu if you want to discuss your idea. Thank you!

**Comment by jay-dee7** [comment]
hey @yisiliu i've set the project up on my local system and also aligned a call with you for Saturday if thats okay?

**Comment by yisiliu** [comment]
@jay-dee7 hey man I am so sorry but I cannot make it the time you scheduled. I did mark some dates as unavailable but I don't why it wasn't applied. Can we schedule a meeting for next week please? Thanks

**Comment by gitcoinbot** [comment]
@jay-dee7 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=100)

**Comment by gitcoinbot** [comment]
@jay-dee7 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=100)

**Comment by jay-dee7** [comment]
@gitcoinbot i'm working on this

**Comment by jay-dee7** [comment]
@yisiliu I realised that i missed the given google doc link and It has additional requirements in it. Most of it looks fine to me, however I wanted to know if this bounty includes developing an IOS app as well?

**Comment by gitcoinbot** [comment]
@jay-dee7 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=100)

**Comment by gitcoinbot** [comment]
@jay-dee7 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=100)

**Comment by jay-dee7** [comment]
@gitcoinbot I'm still working on it.

@yisiliu can you please snooze the bot until next week?

**Comment by gitcoinbot** [comment]
@jay-dee7 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=100)

**Comment by gitcoinbot** [comment]
@jay-dee7 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=100)

**Comment by gitcoinbot** [comment]
@jay-dee7 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=100)

**Comment by gitcoinbot** [comment]
@jay-dee7 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=100)

**Comment by jay-dee7** [comment]
@gitcoinbot im still working on this

**Comment by gitcoinbot** [comment]
@jay-dee7 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=100)

**Comment by gitcoinbot** [comment]
@jay-dee7 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=100)

**Comment by jay-dee7** [comment]
@gitcoinbot im still working on this

**Comment by gitcoinbot** [comment]
@jay-dee7 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=100)

**Comment by gitcoinbot** [comment]
@jay-dee7 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@jay-dee7 due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2362/100024699?snooze=100)
