### ISSUE TITLE
[Bounty] Clubhouse on top of Twitter

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2375]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [ ] Intermediate
  - [x] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 4 weeks
- Bounty Size
  - [x] 2500 USD

## Part 1: Problem Description
Clubhouse has gone viral on the Internet the past week, everywhere in the world. It shows the potential of a socialized audio-only chat room. The success of the Clubhouse is not simply relying on its core audio chat feature. It consists of quite a lot of tweaks and details on their design. Therefore, this bounty is not to copy it. Instead, we just want to show the potential of Mask, being a middle layer on the existing Internet, that can integrate an audio chat room directly on top of Twitter with minimal efforts.

The idea is to inject a chat room in a single tweet, where each person who sees it and have Mask installed can choose to join the room to listen to the discussion, or, raise their hand to speak. In another word, each tweet is a unique chat room, which is designed to be one, with the audio chat functionality. This plugin basically turns each RESTFUL tweet into a REAL TIME discussion. On top of a social media with enough social feature plus the access control system provided by Mask, I believe this would bring our users an alternative choice on the existing social media and it should also bring our (potential) developers more creativeness on how we can play with Mask.

## Part 2: Resources
https://www.joinclubhouse.com/
https://github.com/bestony/neshouse -> an open-source implementation by @bestony in 55 hours

## Part 3: Contact and Support
@yisiliu

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 2500.0 DAI (2500.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2375/100024718).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2375/100024718).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,073,877.73 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by sounak98** [comment]
`neshouse` is dependent on a real-time engagement platform (https://agora.io/en) and a serverless backend (https://leancloud.app). Do you have any preference for such platforms that we need to support the chatrooms on Mask or can I explore?

Also, can we have a chat/call regarding this issue? It would be good to get some things clarified before I submit a plan on Gitcoin for this bounty.

**Comment by developerfred** [comment]
@sounak98 We can host these services on the decentralized like "skynet or arweave"

**Comment by yisiliu** [comment]
@sounak98 I didn't mention it in the issue but we will accept anything but the one he provides in his repo is more preferable. If you are interested, find me at: https://calendly.com/yisiliu

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 9 months from now.
Please review their action plans below:


**1) [alidevjimmy](https://gitcoin.co/alidevjimmy) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2375/100024718?mutate_worker_action=approve&worker=alidevjimmy) | [reject worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2375/100024718?mutate_worker_action=reject&worker=alidevjimmy))_.**

I have the same experience and I happy to help you to complete this the project
**2) [cryptokimie](https://gitcoin.co/cryptokimie) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2375/100024718?mutate_worker_action=approve&worker=cryptokimie) | [reject worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2375/100024718?mutate_worker_action=reject&worker=cryptokimie))_.**

I have a community i can share with them and they'll interact with it
**3) [vsaemi](https://gitcoin.co/vsaemi) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2375/100024718?mutate_worker_action=approve&worker=vsaemi) | [reject worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2375/100024718?mutate_worker_action=reject&worker=vsaemi))_.**

I think I can help my brothers in this project

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2375/100024718).

**Comment by bestony** [comment]
After the NESHouse, ready to start working on this 😎

**Comment by venarius** [comment]
@yisiliu I applied for work. I am halfway done with the PR

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 2500.0 DAI (2500.00 USD @ $1.0/DAI) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2375/100024718)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2375/100024718).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $911,615.29 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
