### ISSUE TITLE
[Bounty] Enabling Partial Encryption

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2550]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [ ] Intermediate
  - [x] Advanced
- Category
  - [x] Mask Core Feature
  - [ ] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 3 weeks
- Bounty Size
  - [x] 3000 USD

## Part 1: Problem Description
Whole post encryption has been enabled as our core feature since Day 1 of the Mask development but we have always been thinking about allowing users to create partial encrypted posts, i.e. users are able to pick a few spots to hide and encrypt. What is this for? 

The best scenario is that, when a school teacher wants to post a [cloze test(https://en.wikipedia.org/wiki/Cloze_test) to their class but couldn't find a place that enables an interactive environment for students to participate easily, they can post it on Twitter directly! All they need to do is to blank out the desired slots and post it with Mask. The students can then directly find it on their teacher's Tweet and take the test. Isn't that amazing? Twitter can become your default class participation platform! **((Kidding))** 

This could be further extended to many applications but we will only focus on the text partial encryption, for now. Interactions are also optional and our desired behavior is that, users without Mask installed or a proper access can only see partial texts and will be able to reveal them once they install Mask or get the access from the author.

e.g.

`The horse raced past the barn ____.`
->
`The horse raced past the barn fell.`

 To realize this, we will also ask you to use the **TypedPost** as the fundamental layer. You will need to consult with @Jack-Works for more info since we sincerely want you to follow our design so as to ease the efforts to extend it. However, after talking to @Jack-Works, if you can come up with something different but useful, we will for sure accept it ;)

## Part 2: Resources
https://github.com/DimensionDev/Maskbook/blob/master/docs/caveats.md

## Part 3: Contact and Support
@yisiliu for ideas and suggestions
@Jack-Works for implementations

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 3000.0 DAI (3000.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2550/100025049).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2550/100025049).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,349,850.74 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by victorZzz0324** [comment]
Conflux Network is an open network built to drive the next generation of global commerce by unlocking the decentralized applications and digital assets of tomorrow. Conflux enables the secure and interoperable flow of assets and data across protocols & applications to create an internet of value for all. By integrating Proof of Work into a Tree Graph architecture, Conflux delivers a robust network with solidity compatibility, zero congestion and low fees.

**Comment by victorZzz0324** [comment]
This bounty to integrate assets on Conflux which supports EVM into Mask Wallet. These assets includes native token CFX and other  ERC20/ERC1155 tokens on Conflux. 

- Resources

https://github.com/DimensionDev/Maskbook
https://confluxnetwork.org/developers/assets
https://developer.conflux-chain.org/
https://confluxscan.io/tokens/erc20
https://confluxscan.io/tokens/erc1155

**Comment by Tedko** [comment]
> This bounty to integrate assets on Conflux which supports EVM into Mask Wallet. These assets includes native token CFX and other ERC20/ERC1155 tokens on Conflux.
> 
> * Resources
> 
> https://github.com/DimensionDev/Maskbook
> https://confluxnetwork.org/developers/assets
> https://developer.conflux-chain.org/
> https://confluxscan.io/tokens/erc20
> https://confluxscan.io/tokens/erc1155

hey maybe wrong issue? -> here u go https://github.com/DimensionDev/Maskbook/issues/2552

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 3000.0 DAI (3000.00 USD @ $1.0/DAI) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2550/100025049)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2550/100025049).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,499,696.02 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by Jack-Works** [comment]
@yisiliu Maybe we should rename/split this bounty. As we discussed before, we may split this into the following parts:

- Parser (parse the SNS native post into a TypedMessage)
- Editor (a rich (?) editor that can create a TypedMessage)
- Transformer pipe (a TypedMessage piped through all transformers and becomes the output)
- Renderer (Render the TypedMessage)

I'd like to give a brief spec of this later. I'll add a new PR for the spec. Please anyone interested follow and review the spec PR.

**Comment by yisiliu** [comment]
Yes it makes sense after we have these components ready but I will leave it here and create another one in the component development. Also, as we discussed, is markdown fit for our requirements? We can build upon it to ease our efforts and users' confusions.

**Comment by Jack-Works** [comment]
> Yes it makes sense after we have these components ready but I will leave it here and create another one in the component development. Also, as we discussed, is markdown fit for our requirements? We can build upon it to ease our efforts and users' confusions. @Jack-Works 

Well, I don't think mapping to markdown is a good idea.

**Comment by Jack-Works** [comment]
close for housekeeping
