### ISSUE TITLE
[Bounty] Integrate Conflux in Mask 

### ISSUE THREAD

**Issue by Miaommmisokay** [DimensionDev/Maskbook#2552]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [ ] Intermediate
  - [x] Advanced
- Category
  - [x] Mask Core Feature
  - [ ] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 4 weeks
- Bounty Size
  - [x] 10000CFX
## Part 1: Problem Description
Conflux Network is an open network built to drive the next generation of global commerce by unlocking the decentralized applications and digital assets of tomorrow. Conflux enables the secure and interoperable flow of assets and data across protocols & applications to create an internet of value for all. By integrating Proof of Work into a Tree Graph architecture, Conflux delivers a robust network with solidity compatibility, zero congestion and low fees.

This bounty to integrate assets on Conflux which supports EVM into Mask Wallet. These assets include native token CFX and other  ERC20/ERC1155 tokens on Conflux. 

## Part 2: Resources
https://github.com/DimensionDev/Maskbook
https://confluxnetwork.org/developers/assets
https://developer.conflux-chain.org/
https://confluxscan.io/tokens/erc20
https://confluxscan.io/tokens/erc1155

## Part 3: Contact and Support
@yisiliu for general information and
@septs for wallet related questions

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 6000.0 DAI (6000.0 USD @ $1.0/DAI)  attached to it as part of the DimensionDev fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2552/100025048).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2552/100025048).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,347,069.28 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by yisiliu** [comment]
**Note the bounty is payed out in CFX preferably**

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 8 months from now.
Please review their action plans below:


**1) [mul1sh](https://gitcoin.co/mul1sh) has started work.**

A integration of conflux into the Mask protocol :)

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2552/100025048).

**Comment by mul1sh** [comment]
@yisilu I'm working on this but I will need more time past the GR9 hackathon, will that be ok or will the bounty be closed after that?

**Comment by yisiliu** [comment]
> @yisilu I'm working on this but I will need more time past the GR9 hackathon, will that be ok or will the bounty be closed after that?

We will extend the ddl. What's your eta?

**Comment by mul1sh** [comment]
> > @yisilu I'm working on this but I will need more time past the GR9 hackathon, will that be ok or will the bounty be closed after that?
> 
> We will extend the ddl. What's your eta?

Thanks give me until April 12th please and i'll be done :)

**Comment by yisiliu** [comment]
> > > @yisilu I'm working on this but I will need more time past the GR9 hackathon, will that be ok or will the bounty be closed after that?
> > 
> > 
> > We will extend the ddl. What's your eta?
> 
> Thanks give me until April 12th please and i'll be done :)

np man thanks!

**Comment by mul1sh** [comment]
@yisiliu so sorry but i'm going to request just a few more days I work on this, im almost there just got a bit derailed by issues on my end.

**Comment by touhonoob** [comment]
Hi @yisiliu  Is this bounty still available for work?

**Comment by Tedko** [comment]
> Hi @yisiliu Is this bounty still available for work?

@touhonoob yes - it is
