### ISSUE TITLE
[Bounty] Build your own Dapp with Mask (1st try)

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2554]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 3 weeks
- Bounty Size
  - [x] 1000 - 3000 USD + a couple of $MASK

## Part 1: Problem Description
Guys, unlock your imaginations with Mask. Take a look at our previous bounties and existing features on Mask and build your own, with minimal efforts. It could be: injecting a game inside of a Tweet, displaying a live streaming while being able to comment as danmaku, displaying a calendly calendar picker for others to book your time for a meeting, and, so much so on. Please consult with us what you want to build, either blockchain apps or non-blockchain apps, and we are more than willing to help you build them. We are aiming for a much better and free Internet within our own hands.

This bounty is aiming to fund at least 4 successful projects so please come and apply ;) Success is rated by if your project(demo) matches your plan. We will continue funding your project towards being merged into our master!!!

## Part 2: Resources
https://github.com/DimensionDev/Maskbook/tree/master/packages/maskbook/src/plugins for example plugins
https://github.com/DimensionDev/Maskbook/issues?q=is%3Aissue+is%3Aopen+label%3A%22Bounty%3A+Open%22 for open bounties

## Part 3: Contact and Support
@yisiliu for ideas
@Jack-Works @guanbinrui @septs for implementations

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 3000.0 DAI (3000.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2554/100025050).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2554/100025050).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,353,531.40 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by Jack-Works** [comment]
@yisiliu I think we should design the third party plug-in system first

**Comment by yisiliu** [comment]
> @yisiliu I think we should design the third party plug-in system first

the clock is ticking so we need to work with them while developing it.

**Comment by antonyip** [comment]
Hello there, 

I've stumbled across this from the gitcoin site. Bounty looking interesting :)

Not too sure where to start asking questions on how to start developing plugins for mask.. please re-direct me to the right direction.

Basically I would like to know an overview on how to setup a dev system so that I could start implementing a plugin on twitter on mask, I'm assuming the code that I write would be portable to facebook and twitter. 

My idea is to build a Secret Santa plugin. Not very innovative, but I believe a good hackathon project :)

Cheers!

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 8 months from now.
Please review their action plans below:


**1) [lordzelkova](https://gitcoin.co/lordzelkova) has started work.**

BullishbearFinance is a defi farming project that looks to have bullish momentum in the bear market acting as the perfect crypto hedge in your Crypto portfolio!

BullishbearFinance will have 3 coins launched all aimed to be a perfect hedge in your Crypto portfolio 
The first of these coins to be launched will be the utility coin CaveCoin partnered with various gitcoin donors to incentivize liquidity via badger/cave pools or mask/cave pools etc. Along with wbtc and weth, uni, sushi, etc...  
CaveCoins utility is as follows 1 percent of all transaction will be dedicated to the team and another 1 percent of all transactions will be dedicated to dedicated to the lp pools 
The key difference in this coin is the tokenomics are new and follows different metics to determine outcomes such as for example apr rates will be determined by the Crypto market as a whole instead of the individual project and what I mean and be explained as such as market cap increases we increase the supply of the coin through higher farming rates this also works in the opposite to when the market is down we decrease the supply creating a relay effect the fees for withdrawals also work this way making fees the exit positions and withdraw higher when the market is up and subsequently lower when the market is down 
The second installment of coins are a governance token with we plan to airdrop to gitcoin donors badger and mask holders, etc... 
The governance token will be as it states a token to govern the platform to decide future decisions with community vault regarding future partnerships and sponsors and community rewards,upgrades, dev rewards etc.
The third installment of coins will be a coin partnered with synthiex to be the ultimate hedge against stocks!

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2554/100025050).

**Comment by Jack-Works** [comment]
@antonyip Hello, the basic idea of a third-party plugin is that you build the DApp on an isolated website. And when it is used in Mask, it will have some special global variable for example `mask.setPluginMeta({ ... })`

**Comment by yisiliu** [comment]
@antonyip I think this is a good idea to start with and yeah the time is quite short so we are not expecting a complicated plugin either. Are you planning to build it on top of Ethereum or completely nothing related to blockchain? And yes @Jack-Works will help you set up a few things to start with to ease your confusions and efforts.

**Comment by antonyip** [comment]
@yisiliu I've played around with the mask.io plugin on the system. I guess the simplest solution to this would be as such..
Say 3 persons in the game, player 1 is the host.

Player 1 enters 3 names into a UI box, 1 box for each name
Player 1 presses the Go Button
System Randomizes names and does some mapping 
1->3 (Player 1 needs to give a gift to Player 3)
2->1
3->2
System Sends 3 twitter messages out (Or partial encryption, which seems like its not ready according to a different bounty)

Un-Encrypted, it would be like "Hello Player3, your Secret Santa is Player 2!"

**Comment by Jack-Works** [comment]
How would you like to communicate with those three people without a server?

**Comment by Jack-Works** [comment]
I'd like to give a brief spec of this later. I'll add a new PR for the spec. Please anyone interested follow and review the spec PR.

**Comment by Jack-Works** [comment]
hello guys RFC is here https://github.com/DimensionDev/Maskbook/pull/2621

**Comment by yozora-cell** [comment]
@yisiliu Hello,I have a plan about new plugin. 
**About Loopss:**
  The Loopss protocol assigns personal tokens representing the trust relationship and authority utility to the added addresses. Based on the underlying credit logic, combined with the upper-level governance, treasury, and interactive contract, Loopss can easily distribute organizational permissions and token transfers, allowing any Individuals and groups evolve community-based capital and DAO organizations with governance capabilities, agreement combination capabilities, and capital management capabilities.
  Loopss credit is equivalent to storing the user relationship on the blockchain, which can not be tampered with and can be verified. The tree-derived DAO system established through credit reduces the cost of establishing an organization on the chain before, and allows organizations to flexibly distribute governance rights based on credit, create sub-organizations, and allow organizations to combine with each other.
**About Loopss-plugin:** 
  Based on the function system of Mask Network, we want to access Loopss tokens so that Loopss users can also use related functions. And let users who use plugins conduct address token trust and token transactions through social platforms. If everything goes in order, I hope to accelerate the establishment of a verifiable social relationship on the blockchain through the Mask Network.

**Comment by yisiliu** [comment]
> @yisiliu Hello,I have a plan about new plugin.
> **About Loopss:**
> The Loopss protocol assigns personal tokens representing the trust relationship and authority utility to the added addresses. Based on the underlying credit logic, combined with the upper-level governance, treasury, and interactive contract, Loopss can easily distribute organizational permissions and token transfers, allowing any Individuals and groups evolve community-based capital and DAO organizations with governance capabilities, agreement combination capabilities, and capital management capabilities.
> Loopss credit is equivalent to storing the user relationship on the blockchain, which can not be tampered with and can be verified. The tree-derived DAO system established through credit reduces the cost of establishing an organization on the chain before, and allows organizations to flexibly distribute governance rights based on credit, create sub-organizations, and allow organizations to combine with each other.
> **About Loopss-plugin:**
> Based on the function system of Mask Network, we want to access Loopss tokens so that Loopss users can also use related functions. And let users who use plugins conduct address token trust and token transactions through social platforms. If everything goes in order, I hope to accelerate the establishment of a verifiable social relationship on the blockchain through the Mask Network.

Thanks for submitting this plugin to us! I am wondering if you have any existing forked repo on this? If so, please create an PR in our repo and we will start review it asap. Thanks!

**Comment by Tedko** [comment]
Since it's from GR9 I will close this first for now. Later we can do similar with other GR or our own hackathon etc.

**Comment by yozora-cell** [comment]
已收到，尽快给您回复。谢谢!
