### ISSUE TITLE
[Demand] Custody NFT tokens

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2586]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

+ [x] Add NFT token #2587
+ [ ] Hide NFT token
+ [ ] Transfer NFT token
+ [ ] Sell NFT token

### Screenshots from ERC20 panel

![image](https://user-images.githubusercontent.com/52657989/111124380-6d06dc00-85ab-11eb-99d1-c039879d3b4e.png)

### Screenshots from MetaMask Mobile APP

![1861615796645_ pic_hd](https://user-images.githubusercontent.com/52657989/111124038-fbc72900-85aa-11eb-99e7-739cb0f9373e.jpg)
![1871615796646_ pic_hd](https://user-images.githubusercontent.com/52657989/111124047-fcf85600-85aa-11eb-9a07-a6c4c0bfb2c8.jpg)
