### ISSUE TITLE
[Bounty] Display v.cent current bid price of the tweet directly on Twitter

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2599]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [x] Beginner
  - [ ] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 1 week
- Bounty Size
  - [x] 500 USD + 500 USD matched by Cent Team!!!

## Part 1: Problem Description
Do I own my tweet? Actually we don't care about it. No matter if Twitter the platform "permits" it or not, Valuables by cent has created a way to help you "own" your Tweet and be able to sell it. Jack Dorsey(@jack@Twitter, founder of Twitter) also sold his first tweet on it (https://v.cent.co/tweet/20, https://twitter.com/jack/status/20). The first step of our cooperation with Valuables is to directly display the current bid price of each Tweet, if it has been offered a bid.
Use their API https://v.cent.co/data/tweet-txn?tweetID=<TWEETID> (e.g. https://v.cent.co/data/tweet-txn?tweetID=20) to get the current bid price and display it within each Tweet card. The UI is all up to you.

## Part 2: Resources
https://v.cent.co/
https://v.cent.co/data/tweet-txn?tweetID=<TWEETID>
https://docs.google.com/document/d/1iXhertpMT5Y8x-2HmemMtpNB6x9sWPUWJq8s-oacweQ/edit

## Part 3: Contact and Support
@yisiliu for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 500.0 DAI (500.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2599/100025148).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2599/100025148).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,510,375.12 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 2 weeks, 2 days from now.
Please review their action plans below:


**1) [mountvase](https://gitcoin.co/mountvase) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2599/100025148?mutate_worker_action=approve&worker=mountvase) | [reject worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2599/100025148?mutate_worker_action=reject&worker=mountvase))_.**

Going to try to implement this one!

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2599/100025148).

**Comment by yisiliu** [comment]
@mountvase hey man can you come up with a plan or something here?

**Comment by MountVase** [comment]
> @MountVase hey man can you come up with a plan or something here?

Yeah, sure!

[] First get familiar with the codebase, figure out how to render something simple on each twitter card.

[] Fetch V.Cent data for each card (twitter status), see if viable.

[] Create Component (/Plugin), style UI.

**Comment by yisiliu** [comment]
> > @MountVase hey man can you come up with a plan or something here?
> 
> Yeah, sure!
> 
> * [ ]  First get familiar with the codebase, figure out how to render something simple on each twitter card.
> * [ ]  Fetch V.Cent data for each card (twitter status), see if viable.
> * [ ]  Create Component (/Plugin), style UI.

Thanks a lot! Regarding the UI, I will consult with our designer @xiazhiming if he has anything in mind.
Also, from the Valuables team:

```
Let's use this endpoint:

https://v.cent.co/data/tweet-txn/latest?tweetID=<TWEETID>

There will only ever be a max of two rows returned: the latest offer as well as the latest sale, if there is any. The API consumer can determine whether the data is an offer or sale based on the type: { "Offer", "Close" } in each row. 
```

Let me know if you need anything else from us and good luck!

**Comment by Shr1ftyy** [comment]
Gotta go F A S T

**Comment by xiazhiming** [comment]
here's the [figma link](https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/Twitter?node-id=8915%3A114) for reference on how we would like it to be displayed. Let me know if you have any questions.

![image](https://user-images.githubusercontent.com/29635388/111630741-9fc00700-882d-11eb-8365-2ac1c077279a.png)

**Comment by iamochuko** [comment]
@yisiliu @Jack-Works Hello, regarding implementation; aside this https://v.cent.co/data/tweet-txn/latest?tweetID=<TWEETID> api; I was expecting some docs link. OR any other supporting DETAIL?

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 500.0 DAI (500.00 USD @ $1.0/DAI) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2599/100025148)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2599/100025148).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,575,015.38 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by Shr1ftyy** [comment]
This is helpful, thank you.

**Comment by yisiliu** [comment]
@iamochuko @Shr1ftyy hey guys @MountVase has submitted a PR on this and I think his implementation seems pretty solid. If you haven't started, please consider working on something else.

**Comment by Shr1ftyy** [comment]
aight, thanks for the heads up.

**Comment by iamochuko** [comment]
Oh, nice one. Thanks.

**Comment by yisiliu** [comment]
but guys feel free to work on other ones if you'd be interested ;)_

**Comment by Tedko** [comment]
hi @xiazhiming sth from my end: should we also follow the `idea market` design guide so - you need to hover somewhere to trigger this functionalities? Or this might be little bit annoying.

Also cc @MountVase - what do you think. we can just add a `v.cent.co` icon and hover to trigger bid price

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 500.0 DAI (500.00 USD @ $1.0/DAI) has been submitted by__:

 1. [@mountvase](https://gitcoin.co/mountvase)



@yisiliu please take a look at the submitted work:
* [PR](https://github.com/DimensionDev/Maskbook/pull/2622) by @mountvase

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2599/100025148)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2599/100025148).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,688,965.72 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 500.00000  DAI (500.0 USD @ $1.0/DAI) has been granted to @mountvase for this issue from @yisiliu. ⚡️ 

Nice work @mountvase! To redeem your tip, login to Gitcoin at https://gitcoin.co/explorer and select 'Claim Tip' from dropdown menu in the top right, or check your email for a link to the tip redemption page. 

 * $1957183.82 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://discord.com/invite/83BK5z55yB'>Gitcoin's Discord</a>

**Comment by yisiliu** [comment]
This feature will be merged in our new version. Cheers!

**Comment by Jack-Works** [comment]
> This feature will be merged in our new version. Cheers!

which version is accepted? who will get the DAI?

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__The funding of 500.0 DAI (500.00 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @mountvase.__  

 

Additional Tips for this Bounty:
* yisiliu tipped 500.0000 DAI worth 500.0 USD to mountvase.

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2599/100025148)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,373,620.93 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
