### ISSUE TITLE
[Bounty] Integrate NEAR wallet into Mask

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2602]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [ ] Intermediate
  - [x] Advanced
- Category
  - [ ] Mask Core Feature
  - [ ] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [x] Other
    - [x] Cryptocurrency Wallet
- Time Commitment
  - [x] 4 weeks
- Bounty Size
  - [x] 5000 USD

## Part 1: Problem Description
NEAR exists to accelerate the world’s transition to open technologies by growing and enabling a community of developers and creators. NEAR is a decentralized application platform that secures high value assets like money and identity with the performance necessary to make them useful for everyday people, putting the power of Open Finance and the Open Web in their hands. NEAR’s unique account model allows developers to build secure apps that consumers can actually use similarly to today’s web apps, something which requires multiple second-layer add-ons on other blockchains.

As the first step of our cooperation, we, Mask Network, would like to integrate NEAR as one of our default supported blockchain system in our internal Mask Wallet, so that further on-chain interactions would happen directly within Mask Network without leaving the platform. We believe this would further help us attract more users from different projects, aiming at different goals to maximize users experiences in the broad blockchain world.

We are now renovating our internal wallet and targeting at finishing that by the end of April. If you are interested in this bounty, please make sure that you contact us first to see how our structure looks like and proceed to the development afterwards.

## Part 2: Resources
https://wallet.near.org/
https://github.com/DimensionDev/Maskbook/tree/master/packages/maskbook/src/plugins/Wallet

## Part 3: Contact and Support
@yisiliu @septs @Jack-Works 
[Mask Network Discord Server](https://discord.gg/4Xccj7a75Q)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 5000.0 DAI (5000.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025150).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025150).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,498,450.63 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 5000.0 DAI (5000.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,498,450.63 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 8 months from now.
Please review their action plans below:


**1) [developerfred](https://gitcoin.co/developerfred) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151?mutate_worker_action=approve&worker=developerfred) | [reject worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151?mutate_worker_action=reject&worker=developerfred))_.**

I am familiar with Mask and NEAR would love to build this integration.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151).

**Comment by gitcoinbot** [comment]
@developerfred Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151?snooze=100)

**Comment by developerfred** [comment]
@gitcoinbot I'm working <3

**Comment by gitcoinbot** [comment]
@developerfred Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@developerfred due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151?snooze=1) | [3 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151?snooze=3) | [5 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151?snooze=5) | [10 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151?snooze=10) | [100 days](https://gitcoin.co/issue/DimensionDev/Maskbook/2602/100025151?snooze=100)

**Comment by r5n** [comment]
hey, @developerfred are you still working on this?

**Comment by developerfred** [comment]
@r5n Yes, now the integration will be perfect because the aurora was launched.

**Comment by Tedko** [comment]
Close this one since aurora is already supported
