### ISSUE TITLE
[Bounty] Now that assets on opensea can directly display on Twitter, why not buy or sell it too?

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2608]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 1000 USD

## Part 1: Problem Description
Yes why not?
Along with the new feature here, we would like to improve the logic of displaying the logic of displaying the NFT. In #2022 #2170, one needs to include the opensea url in the encrypted post to display it. However, we would like to detect the url directly from the plain post this time, i.e. the url doesn't have to be in the encrypted post. This will help spread out the words.

## Part 2: Resources
#2170 
https://github.com/ProjectOpenSea/opensea-js

## Part 3: Contact and Support
@yisiliu @sounak98 @Jack-Works 
https://discord.gg/4Xccj7a75Q

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 1000.0 DAI (1000.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2608/100025156).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2608/100025156).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,476,982.36 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by yisiliu** [comment]
@sounak98 finally do you want to work on it?

**Comment by sounak98** [comment]
Yeah sure, would love to work on it.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 2 weeks, 1 day from now.
Please review their action plans below:


**1) [az111z2](https://gitcoin.co/az111z2) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2608/100025156?mutate_worker_action=approve&worker=az111z2) | [reject worker](https://gitcoin.co/issue/DimensionDev/Maskbook/2608/100025156?mutate_worker_action=reject&worker=az111z2))_.**

We are an ambitious team and we hope for success, so we can move forward and we have been granted the grant of support for us, and we will be, according to your story

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2608/100025156).

**Comment by Tedko** [comment]
@sounak98 hi https://github.com/DimensionDev/Maskbook/issues/2651#issuecomment-805454116

**Comment by guanbinrui** [comment]
closed by #2608.
