### ISSUE TITLE
[Bounty] Integrate Quickswap into Mask

### ISSUE THREAD

**Issue by qinghuii** [DimensionDev/Maskbook#2645]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 1000 USD

## Part 1: Problem Description

Polygon (formerly Matic Network) is the first well-structured, easy-to-use platform for Ethereum scaling and infrastructure development. Its core component is Polygon SDK, a modular, flexible framework that supports building and connecting Secured Chains like Plasma, Optimistic Rollups, zkRollups, Validium etc and Standalone Chains like Matic POS, designed for flexibility and independence. 

We plan to first integrate Quickswap (a next-generation layer 2 decentralized trading platform), and gradually complete the integration with Polygon, so users can trade assets more quickly and with near-zero gas fee.

## Part 2: Resources

https://quickswap.exchange/#/swap
https://polygon.technology/
https://mask.io

## Part 3: Contact and Support

@yisiliu and @guanbinrui 
[Mask Discord Server](https://discord.com/invite/4SVXvj7)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 1000.0 DAI (1000.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2645/100025307).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2645/100025307).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,614,073.65 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by developerfred** [comment]
@yisiliu I have a question about the provider, whether I updated Walletconnect and metamask or just WEB3?
ref: https://docs.matic.network/docs/develop/key-management/walletconnect/

**Comment by yisiliu** [comment]
@developerfred in the first stage I'd prefer to only support Walletconnect plus memtamask support, not our internal wallet.

**Comment by developerfred** [comment]
@yisiliu thanks!

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 1000.0 DAI (1000.00 USD @ $1.0/DAI) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2645/100025307)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/2645/100025307).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,571,976.31 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 1 week, 1 day from now.
Please review their action plans below:


**1) [developerfred](https://gitcoin.co/developerfred) has started work.**

Integration Layer2 on Maskbook

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/2645/100025307).

**Comment by MysticRyuujin** [comment]
This should be Sushi Swap...which is also on Matic...

**Comment by yisiliu** [comment]
> This should be SushiSwap...which is also on Matic...

Is suhiswap also on matic? I guess you were referring to [this](https://cointelegraph.com/news/all-you-can-eat-sushiswap-deploys-contracts-on-five-new-networks) right?

**Comment by MysticRyuujin** [comment]
Yes, if you go to exchange.sushi.com and connect to a Matic RPC endpoint, it works perfectly fine, same as QuickSwap.

**Comment by Tedko** [comment]
> Yes, if you go to exchange.sushi.com and connect to a Matic RPC endpoint, it works perfectly fine, same as QuickSwap.

wow thx for telling us @MysticRyuujin yeah definitely should integrate as well

**Comment by Tedko** [comment]
@developerfred hows the progress? also hows sia hah

**Comment by r5n** [comment]
Hey, @developerfred are you working on this also?
if not can I take over

**Comment by Tedko** [comment]
@yisiliu lets close this bounty since binrui already working on this

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__The funding of 1000.0 DAI  (1000.00 USD @ $1.0/DAI) attached to this issue has been **cancelled** by the bounty submitter__

 
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $2,074,381.89 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
