### ISSUE TITLE
Roadmap: v1.7.1

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#268]
- [x] update gun to the newer version
- [x] add iOS and Android version links in the Readme and the options page
- [x] make iOS and Android version easy to use

**Comment by neruthes** [comment]
Can we make #70 and #76 in this version, or will we have to put them off to 1.8.0?

**Comment by Jack-Works** [comment]
> Can we make #70 and #76 in this version, or will we have to put them off to 1.8.0?

No, 1.7.1 will be a small update. We will not introduce new features

**Comment by neruthes** [comment]
> > Can we make #70 and #76 in this version, or will we have to put them off to 1.8.0?
> 
> No, 1.7.1 will be a small update. We will not introduce new features

ACK.

**Comment by Tedko** [comment]
How’s Gun’s newest ver!
