### ISSUE TITLE
[Demand] Add Information Card (Snapshot)

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2721]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (Snapshot)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

+ Add Information Card of the given proposal and its structure looks like the screenshot in Part3.
+ The card should be wrapped in a `<Card />` component with a solid border.

## Part 3: Expected Behavior

![image](https://user-images.githubusercontent.com/52657989/113106721-abe89300-9235-11eb-9e4d-b6725e4aaebd.png)
