### ISSUE TITLE
[Demand] Add Result Card (Snapshot)

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2722]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (Snapshot)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

+ Add Result Card of the given proposal and its structure looks like the screenshot in Part3.
+ The card should be wrapped in a <Card /> component with a solid border.

## Part 3: Expected Behavior

![image](https://user-images.githubusercontent.com/52657989/113107047-04b82b80-9236-11eb-8e9f-022dd21ef790.png)
