### ISSUE TITLE
[Demand] snapshot vote confirm modal ui (Snapshot)

### ISSUE THREAD

**Issue by zhouhanseng** [DimensionDev/Maskbook#2788]
## Catalogue

- [x] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (Snapshot)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

https://twitter.com/Zhouhancheng/status/1377830760996950016

![image](https://user-images.githubusercontent.com/63733714/114003529-64df4b00-9890-11eb-8c95-758aad3626c7.png)

Click the Vote button, popup the confirm modal.

## Part 3: Expected Behavior

The content of modal should equal to the one at snapshot website, and the style of the modal just keep using our own.

https://snapshot.org/#/dai/proposal/QmerQSKDkycu4QwTa5Bu4qYV2BMvVbkfAL9TqGrREsiRkw

![image](https://user-images.githubusercontent.com/63733714/114003718-92c48f80-9890-11eb-9092-41ebcb2fd321.png)

![image](https://user-images.githubusercontent.com/63733714/114003900-b982c600-9890-11eb-84b4-f930cd88e872.png)

**Comment by guanbinrui** [comment]
closed by #2697.
