### ISSUE TITLE
[Demand] Add ECDHE(ephemeral) encryption support

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2790]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [x] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
WIP

**Comment by Jack-Works** [comment]
we have that now
