### ISSUE TITLE
[Demand] Switch Provider Button

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2921]
## Catalogue

- [X] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (Trader)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

Add a switch provider button and let the user switch to another provider if the current provider is down.

![image](https://user-images.githubusercontent.com/52657989/115356350-2598ee80-a1ee-11eb-8b63-893f62c7fd0a.png)
