### ISSUE TITLE
[Bounty] Asking for a brief/documentation of plugin Fileservice 

### ISSUE THREAD

**Issue by azuic** [DimensionDev/Maskbook#2947]
## Catalogue

- Platform
  - [ ] Gitcoin
  - [ ] Hackerlink
  - [x] Mask
- Experience
  - [x] Beginner
  - [ ] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [x] Security/Cryptography Feature
  - [x] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment

- Bounty Size

## Part 1: Problem Description
Similar to the File Service plugin, but instead of upload file on the compose interface and preview in the post, we are working with audio recording in the compose interface and audio playing in the post interface (only decrypted after verified the user has paid). I have finished the UI of the recorder and the player, and since the functionality is almost the same, can I get a brief of the apis/components/files in `fileservice` so that I can refer as a template to insert into maskbook as a plugin?

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)

**Comment by Tedko** [comment]
it's for AIR right? cc @azuic @yisi

**Comment by azuic** [comment]
Yes.
