### ISSUE TITLE
[Demand] The Claim Your Tokens Dialog

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3033]
## Catalogue

- [x] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (ITO)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

Be able to claim one's owned tokens in multiple ITO rounds.

+ TOKENs are not claimable if those claimed TOKENs were locked in the contract.
+ TOKENs are claimable if the locking period is expired.

### Token Card

It should present a TOKEN CARD component for each claimable or unclaimable TOKENs. A TOKEN with the same address but has a different locking period will render multiple TOKEN CARD components. 

E.g., If an account has got `1` unlocked TOKEN A, with `2` locked TOKEN A in locked period `t1` and `3` locked TOKEN A in locked period `t2`. It should render three TOKEN CARD components.

+ TOKEN A with unlocked amount `1`.
+ TOKEN A with locked amount `2` in expiration time `t1`.
+ TOKEN A with locked amount `3` in expiration time `t2`.

### Claim Button

+ It should be disabled if nothing to claim.
+ It should be enabled if it has got any TOKENs to be claimed.
+ Click this button is meant to claim all of the claimable TOKENs at that time.

## Notes

+ [Figma](https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/Twitter?node-id=11150%3A268323)
