### ISSUE TITLE
[Demand] Switch plugins on and off

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#3066]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Roadmap

Before started, the following things should be done:

- [x] Add a new namespaced settings to store the state of whether each plugin is on or off
- [x] Implement `Plugin.__Host.EnabledReporter`

Then the process can be done plugin-by-plugin. For a certain plugin, the following steps should be taken

```md
1. [ ] Migrate the plugin to register with the new plugin infra.
2. [ ] Make sure side effects get cleanup by the AbortSignal
3. [ ] Display the switch control in the UI for this plugin (if it supports turn on/off)
```

The following plugins needs to migrate:

- [x] Collectible (#3462) (@guanbinrui)
- [x] File Service (#3508) (@septs)
- [x] Gitcoin (#3495) (@UncleBill)
- [x] ITO (https://github.com/DimensionDev/Maskbook/pull/3543 @zhouhanseng)
- [x] NFT (#3465) (@guanbinrui)
- [x] Polls (#3500) (@UncleBill)
- [x] RedPacket (#3430) (@Jack-Works )
- [x] Snapshot (#3458) (@zhouhanseng)
- [x] Trader #3554 (@guanbinrui)
- [x] Transak (#3496) (@UncleBill)
- [x] VCent (#3497) (@UncleBill)
- [x] Airdrop (#3471) (@guanbinrui)
- [x] Wallet (#3483) (@guanbinrui)
- [x] <s>Ethereum (#3483) (@guanbinrui)</s>
- [x] dHEDGE (#3653) (@guanbinrui)

After we migrated all plugins, the old plugin loader should be removed.

**Comment by septs** [comment]
migrate plugin to standalone subpackage (`packages/plugins/*`)

need pre-migrate some files:

1. migrate `packages/maskbook/src/database/Plugin` to `@masknet/plugin-infra`
2. migrate `packages/maskbook/src/plugins/utils` to `@masknet/plugin-infra`
3. migrate `packages/maskbook/src/utils` to `@masknet/shared`
4. migrate `packages/maskbook/src/protocols` to `@masknet/protocols`
5. etc

**Comment by Jack-Works** [comment]
Moving plugin to a standalone package is a future work but yes, I'll do it later.
