### ISSUE TITLE
[Demand] Compose red packet payload by querying past logs

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3123]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (RedPacket)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

The graph APIs used by now are not robust enough and easy to break. And some important features are not supported by all chains. Then we may need to fetch red packet payloads by querying the past events.

API: https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html?highlight=past%20logs#getpastevents

**Comment by zhouhanseng** [comment]
Bsc mainnet is supported if we put all data in event, and we need to deploy for bsc seperately anyway. So we should use web3 query as a failover when graph fails

**Comment by guanbinrui** [comment]
Closed by #3629.
