### ISSUE TITLE
[Bounty] Update Japanese translate

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#3196]
## Catalogue

- Platform
  - [ ] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [ ] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [ ] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [x] Other
    - [x] Update [packages/maskbook/src/_locales/ja/messages.json](https://github.com/DimensionDev/Maskbook/blob/master/packages/maskbook/src/_locales/ja/messages.json) File
- Time Commitment
  - [x] *PLACEHOLDER*
- Bounty Size
  - [x] *PLACEHOLDER*

## Part 1: Problem Description

Update Japanese translate

Now more than 40% unfilled i18n field

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)

## Part 3: Contact and Support

@septs

**Comment by septs** [comment]
CC @blank71 @mizphses

**Comment by tiaramoe** [comment]
What will be the rewards of Bounty this time?

**Comment by blank71** [comment]
@septs Bounty? 0x1caAadDd43068A019dbEf4E5ecA1620eaDeA7F14

**Comment by septs** [comment]
@yisiliu

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 500.0 DAI (500.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/3196/100025795).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/3196/100025795).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $1,593,940.61 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by yisiliu** [comment]
@blank71 I've opened one on gitcoin for record. Can you please apply at https://gitcoin.co/issue/DimensionDev/Maskbook/3196/100025795 and I can pay you there? Thanks

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 5 months from now.
Please review their action plans below:


**1) [blank71](https://gitcoin.co/blank71) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/DimensionDev/Maskbook/3196/100025795?mutate_worker_action=approve&worker=blank71) | [reject worker](https://gitcoin.co/issue/DimensionDev/Maskbook/3196/100025795?mutate_worker_action=reject&worker=blank71))_.**

Done!! 

[Bounty] Update Japanese translate · Issue #3196 · DimensionDev/Maskbook
https://github.com/DimensionDev/Maskbook/issues/3196#issuecomment-851348515

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/3196/100025795).

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work for 500.0 DAI (500.0 USD @ $1.0/DAI) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/3196/100025795)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/3196/100025795).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $1,624,574.28 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by septs** [comment]
@blank71 Sorry, I hope you can provide some additional updates, after the #3275 merge

**Comment by yisiliu** [comment]
@blank71 payed.

**Comment by septs** [comment]
![image](https://user-images.githubusercontent.com/3842474/120567370-2efbb480-c444-11eb-915d-42fa079ee21d.png)

@blank71 I hope to modify, shorten the text length

**Comment by blank71** [comment]
@septs It's shortest translation. "リスティング" can write "ﾘｽﾃｨﾝｸﾞ" to make shorten but it looks bad and nonsense for me and Japanese people doesn't use this. I know Windows, iOS or Android(AOSP) don't use this, but Samsung Galaxy or other some kinds of mobile phone do this because of less UI space.

What's your opinion? Change to "ﾘｽﾃｨﾝｸﾞ" or not?
