### ISSUE TITLE
[Bounty] Update Chinese (Traditional) translate

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#3263]
## Catalogue

- Platform
  - [ ] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [ ] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [ ] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [x] Other
    - [x] Update [packages/maskbook/src/_locales/zh/messages.json](https://github.com/DimensionDev/Maskbook/blob/master/packages/maskbook/src/_locales/zh/messages.json) File
- Time Commitment
  - [x] 20 hours
- Bounty Size
  - [x] 500 DAI

## Part 1: Problem Description

Update Traditional Chinese (Dialect: Taiwanese) translate

Now more than 47% unfilled i18n field

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)

## Part 3: Contact and Support

@septs and @yisiliu

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 500.0 DAI (500.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/3263/100025796).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/3263/100025796).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $1,594,440.61 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 5 months from now.
Please review their action plans below:


**1) [touhonoob](https://gitcoin.co/touhonoob) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/DimensionDev/Maskbook/3263/100025796?mutate_worker_action=approve&worker=touhonoob) | [reject worker](https://gitcoin.co/issue/DimensionDev/Maskbook/3263/100025796?mutate_worker_action=reject&worker=touhonoob))_.**

Who am I:
I am a native Traditional Chinese user from Taipei, Taiwan.

Steps to complete the task:
- Update https://github.com/DimensionDev/Maskbook/blob/master/packages/maskbook/src/_locales/zh/messages.json by translating messages in https://github.com/DimensionDev/Maskbook/blob/master/packages/maskbook/src/_locales/en/messages.json

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/3263/100025796).

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work for 500.0 DAI (500.0 USD @ $1.0/DAI) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/3263/100025796)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/3263/100025796).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $1,596,570.12 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by septs** [comment]
@yisiliu
