### ISSUE TITLE
Security milestone, The first one

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#3323]
Things to be done in this security milestone:

- [x] Block install scripts by default (#5731)
- [x] CVE-2021-42574 protection, should be done as a Webpack plugin. (#5443)
- [x] CVE-2021-42694 protection, same as above (#5443)
- [x] ~~Stop using our proxy to Github packages to reduce the attack surface.~~
    - [x] ~~Remove Circle CI?~~
- [x] ~~Reproducible build by default~~
- [ ] ~~Compare tools for different builds~~
- [x] Enable SES lockdown (#5759)
- [ ] Enable CSP (#5770)
- [x] Enable Trusted Types

**Comment by Jack-Works** [comment]
most of them are done.
