### ISSUE TITLE
[Demand] The Past tabl of the Red Packet composition dialog

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3325]
## Catalogue

- [x] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (Red Packet)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

Disable the Past tab if a no-Ethereum Network was selected.

## Notes
