### ISSUE TITLE
[Demand] Complete the wallet creation progress on the SNS end

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3329]
## Catalogue

- [x] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (Wallet)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/Twitter?node-id=2235:0&viewport=-3600,1391,1.225877046585083

**Comment by UncleBill** [comment]
Done in https://github.com/DimensionDev/Maskbook/pull/3298 (f353dd8c702e8c1663ee27c4f34a9197902220c3)
