### ISSUE TITLE
[Bounty] Integrate Reality Card, an NFT prediction market, in Mask Plugin

### ISSUE THREAD

**Issue by tzhan28** [DimensionDev/Maskbook#3342]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] ~400 $MASK or $2000~ 800 $MASK or $4000, matched by the Reality team

## Part 1: Problem Description

**Background**
Prediction market is fun to play with friends so naturally it should live on social networks. Mask would love to see all sorts of prediction markets thrive on us. Notable ones including Augur, Omen (powered by gnosis), Polymarket, Reality card etc

Reality card is a new breed of prediction market that makes the result ownable by turning betting options into purchasable NFTs. People will likely have a strong desire to show off their bets both before the result is revealed and after, if it is in their favor. This could be very powerful coupled with Mask dapplet.

**Solution**
Build a reality card plugin on Mask. The UI could resemble Dhedge in a card style with different tabs serving different purposes

![image](https://user-images.githubusercontent.com/45725943/121800209-102ac880-cc63-11eb-8e99-4e9788c7d387.png)
_Dhedge UI_

![image](https://user-images.githubusercontent.com/45725943/121801359-83cfd400-cc69-11eb-974e-9409ac72ad27.png)
_Detail page for a market on Reality cards_

![image](https://user-images.githubusercontent.com/45725943/121801560-82eb7200-cc6a-11eb-9e35-cd34c42db54f.png)
_Purchase page for an option on Reality cards_

The detail page looks a bit messy and less user friendly for a small card ui on mask plugin so it might need to be trimmed down into a simpler table. I would recommend default tab with title, market description, options and respective rental prices and the rent button. second page could include price history and chart and perhaps leaderboard. You could also change it to whichever is the best for users.

Reality card will first launch on xdai but will soon expand to other chains. So it's worth it to start early although Mask doesnt support xdai yet.

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://realitycards.io/
- https://github.com/RealityCards

## Part 3: Contact and Support
@yisiliu for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q
Reality Cards discord server: https://discord.com/invite/Pqy5x3KnQd

**Submission Requirements**
Please include demo to show the integration is working.

**Winner Announcement Date**
Winners will be announced at the conclusion of Gitcoin 10 Hackathon

**Judging Criteria**
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 250.0 ETH (657652.87 USD @ $2630.61/ETH)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/3342/100025892).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/3342/100025892).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $2,661,083.04 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by yisiliu** [comment]
We are doubling this bounty after talking to the Reality team so the bounty is now 800 $MASK or $4000. Thanks a lot to the Reality team!!!!!

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 1 day, 2 hours from now.
Please review their action plans below:


**1) [irhonin](https://gitcoin.co/irhonin) has started work.**

Integrate Reality Card as described in the description.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/3342/100025892).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 2 months, 2 weeks ago.
Please review their action plans below:


**1) [irhonin](https://gitcoin.co/irhonin) has started work.**

Integrate Reality Card, In Mask Plugin.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/3342/100025892).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 400.0 MASK (5060.00 USD @ $14.34/MASK) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/3342/100025892)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/3342/100025892).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $7,131,687.97 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by iRhonin** [comment]
Hello, are you still interested to integrate RealityCards?

I resolved conflicts and migrated APIs to RealityCards v12 and the [PR](https://github.com/DimensionDev/Maskbook/pull/4785) is ready to review and merge. 

@guanbinrui @Jack-Works

**Comment by tzhan28** [comment]
Yes! Will revert to the tech team

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LindaMask** [comment]
Closed, @iRhonin will revisit once reality card relaunches.
