### ISSUE TITLE
[Demand] Track on-going transactions

### ISSUE THREAD

**Issue by zhouhanseng** [DimensionDev/Maskbook#3415]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [x] interact with Blockchain
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
https://github.com/DimensionDev/Maskbook/issues/3398

## Part 2: Problem to Solve
The status of a transaction is available to the original component which sends it. E.g. the redpacket is listening to the status of the transaction which claims it, but if you share the redpacket then send it under another twitter, it won't listen to the transaction which leads to an incorrect UI: it shows a 'claim' button rather than the disabled 'claiming' button.

## Part 3: Expected Behavior
Manage a global mappings `{'txid': TransactionStatusType}` to track on-going transactions.
