### ISSUE TITLE
[Demand] Revamp Plugin UI

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3654]
## Catalogue

- [x] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

The following plugins need to be revamped:

+ [x] Red Packet (@UncleBill) [Red Packet Token UI](https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/Twitter?node-id=4312%3A216588) #3718
+ [ ] ITO (@zhouhanseng) [Market UI](https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/Twitter?node-id=357%3A979)
+ [ ] Collectible [NFT UI](https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/Twitter?node-id=8896%3A0)
+ [ ] File Service (@septs  @lelenei)  [File Service Plugin UI](https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/Twitter?node-id=12111%3A334425) / [File Service Landing Page UI](https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/Twitter?node-id=12369%3A277319)
