### ISSUE TITLE
[Demand] Revist Collectible Plugin

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3761]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (Collectible)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

The Rarible team has announced their [NFT protocol API](https://docs.rarible.com/). We may use it to complement the collectible plugin.

Some features need to be added:

+ [ ] Listing an NFT token.
+ [ ] Place a bid on an NFT token.
+ [ ] Fulfill a bid on an NFT token.
