### ISSUE TITLE
[Demand] Fiat on-ramps on non-Ethereum networks

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3802]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (Transak)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

Able to exchange fiat money to cryptocurrencies with Transak on non-Ethereum networks.
