### ISSUE TITLE
[Demand] Integrate Unstoppable Domains

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3978]
## Catalogue

- [ ] UI/UX
- [x] Mask Core Feature (NFTs Tab)
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

+ Use the Twitter id as the SECOND LEVEL domain name to resolve to an Ethereum account. Below are the supported TOP LEVEL domain names.

| Name Service | Supported Domains |
| :--- | :--- |
| Zilliqa Name Service \(ZNS\) | `.zil` |
| Ethereum Name Service \(ENS\) | `.eth`, `.kred`, `.xyz`, `.luxe` |
| Unstoppable Name Service \(UNS\) | `.crypto`, `.nft`, `.blockchain`, `.bitcoin`, `.coin`, `.wallet,` `.888`, `.dao`, `.x` |

**Comment by guanbinrui** [comment]
```
const { default: Resolution } = require('@unstoppabledomains/resolution');
const resolution = new Resolution();

function resolveCustomRecord(domain, record) {
  resolution
    .records(domain, [record])
    .then((value) => {
        console.log(`Domain ${domain} ${record} is:`)
        console.log(value)
    })
    .catch(console.error);
}

resolveCustomRecord('homecakes.crypto', 'crypto.ETH.address');
```
