### ISSUE TITLE
[Demand] Replaint DApps on Arbitrum

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3997]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

+ [ ] Red Packet
+ [ ] ITO
