### ISSUE TITLE
[Bounty]  Integrate Barnbridge, a defi app for risk management and fixed income, in Mask Plugin

### ISSUE THREAD

**Issue by tzhan28** [DimensionDev/Maskbook#4018]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 300 $MASK or $2000 + 50 $BARN

## Part 1: Problem Description

**Background**
BarnBridge is a risk tokenizing protocol. It aims to reduce the risks associated with DeFi, such as inflation risk, market price risk, and cash-flow volatility risk. By letting users select a risk profile, BarnBridge can redistribute risk via tokenized, liquid tranches. BarnBridge does this with its SMART Yield, SMART Exposure, and SMART Alpha products, all of which address a specific DeFi risk category.

Previously defi plugins on Mask, like the trading widgets powered by 0x and Uniswap, has been plagued by high ETH gas prices.  However with the launch of polygon and BSC integration, the problem should have been largely resolved. Fixed income app which was hindered by monstrous ETH gas price is now very much accessible. 

**Solution**
Create a plugin that integrate barnbridge.  The UI could resemble Dhedge & Pooltogether in a card style with different tabs serving different purposes. 

![image](https://user-images.githubusercontent.com/45725943/121800209-102ac880-cc63-11eb-8e99-4e9788c7d387.png)
_Dhedge Plugin UI_

![image](https://user-images.githubusercontent.com/45725943/121802352-65200c00-cc6e-11eb-8cb4-b79ac566972a.png)
_Pooltogether pool list_

![image](https://user-images.githubusercontent.com/45725943/121802366-7c5ef980-cc6e-11eb-867a-feb075027ebb.png)
_Pooltogether deposit page_

Default page could be the pool list with senior tranche liquidity and return, junior tranche liquidity and return, and other basic info like shown in the official website (IMO it's clean enough for porting directly) . Once click deposit, users will be taken to deposit page where detailed info is displayed.

A second tab would be my page where all my portfolios are displayed

Anylink from Barnbridge on Twitter could trigger the plugin ( could have some slightly different treatment). The tab order can be changed, corresponding landing and ending page needs to be added. Share button is a must. 

Language like 
**I just deposited $aa worth of xxx token in a high yield fixed income product can I make money?** 
should be added to help spread the word.

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://barnbridge.com/
- https://docs.barnbridge.com/

## Part 3: Contact and Support
@yisiliu for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q
Barnbridge discord server: https://discord.gg/barnbridge

**Submission Requirements**
Please include demo to show the integration is working.

**Winner Announcement Date**
Winners will be announced at the conclusion of Open DeFi Hackathon

**Judging Criteria**
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 300.0 MASK (1956.0 USD @ $6.52/MASK)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/4018/100026347).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/4018/100026347).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $3,570,887.25 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 5 months, 3 weeks ago.
Please review their action plans below:


**1) [lynnuxdev](https://gitcoin.co/lynnuxdev) has started work.**

I will integrate Barnbridge, a defi app for risk management and fixed income, as a plugin for Mask.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/4018/100026347).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 1000.0 USDC (1000.0 USD @ $1.0/USDC)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/4018/100028469).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/4018/100028469).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $4,183,346.33 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 1000.0 USDC (1000.0 USD @ $1.0/USDC)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/4018/100028468).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/4018/100028468).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $4,183,346.33 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by LindaMask** [comment]
@lynnuxdev can you please reach out to me on telegram @lin_dao so we can take you through the bounty program?

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 1 week from now.
Please review their action plans below:


**1) [henricow](https://gitcoin.co/henricow) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/dimensiondev/maskbook/4018/100028468?mutate_worker_action=approve&worker=henricow) | [reject worker](https://gitcoin.co/issue/dimensiondev/maskbook/4018/100028468?mutate_worker_action=reject&worker=henricow))_.**

Over the last two days, I have gone through Mask and Barnbridge's code and I would like to take this on.

Rest of plan:
Develop solution on testnet (Avax)
Discuss, review
Refine
Submit

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/4018/100028468).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 2 weeks, 3 days ago.
Please review their action plans below:


**1) [ajand](https://gitcoin.co/ajand) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/dimensiondev/maskbook/4018/100028468?mutate_worker_action=approve&worker=ajand) | [reject worker](https://gitcoin.co/issue/dimensiondev/maskbook/4018/100028468?mutate_worker_action=reject&worker=ajand))_.**

I want to integrate barnbridge into the mask plugin

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/4018/100028468).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__The funding of 2000.0 USDC  (2000.0 USD @ $1.0/USDC) attached to this issue has been **cancelled** by the bounty submitter__

 
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $3,677,689.52 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
