### ISSUE TITLE
[Bounty] Integrate Enzyme, an asset management platform, in Mask Plugin

### ISSUE THREAD

**Issue by tzhan28** [DimensionDev/Maskbook#4041]
## Catalogue

- Platform
  - [x] #4139
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 300 $MASK or $2000

## Part 1: Problem Description

**Background**
Enzyme is an On Chain Asset Management platform. It's a fast & cost-effective way to build, scale and monetize investment strategies. Enzyme is on eth mainnet. 

**Solution**
Create a plugin that integrate Enzyme.  The UI could resemble Dhedge in a card style with different tabs serving different purposes. 

![image](https://user-images.githubusercontent.com/45725943/121800209-102ac880-cc63-11eb-8e99-4e9788c7d387.png)
_Dhedge Plugin UI_

Default page could be the strategy  asset under management, and other basic info shown in the official website  . 
A second tab may be a page for price chart
A third tab may be my page where all my investments are displayed

Anylink from Enzyme on Twitter could trigger the plugin ( could have some slightly different treatment). The tab order can be changed, corresponding landing and ending page needs to be added. Share button for such a social game is a must. 

Language like 
**I just investd xxx dollar into xxx pool, can I make money?** 
should be added to help spread the word.

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://app.enzyme.finance/depositor/leaderboard
- https://docs.enzyme.finance/

## Part 3: Contact and Support
@yisiliu for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q
Enzyme discord server: https://discord.com/invite/2HDzKxtNAC

**Submission Requirements**
Please include demo to show the integration is working.

**Winner Announcement Date**
Winners will be announced at the conclusion of Open Defi Hackathon

**Judging Criteria**
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by iamzubin** [comment]
Starting to work on this bounty
