### ISSUE TITLE
[Demand] Refactor NFT wallet to use built-on hooks

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#4233]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

+ [ ] Move `useEthereumName` to `@masknet/web3-shared`.
+ [ ] Use `useSurfaceRecognizedIdentity` to load the identity information on the profile page.
