### ISSUE TITLE
[Bounty] NFT profile page

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#4294]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [x] Mask Core Feature
  - [ ] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 4 weeks
- Bounty Size
  - [x] 200 MASK or 2000 USD

## Part 1: Problem Description
We created a bounty #2236 , months ago, that's looking for someone in the community to help us enhance the capability of local rendering, allowing users to "decorate" their Twitter profile page with non-static media resources. It seems match the latest NFT profile photo trending and since our team has made the nft profile photo possible, we are here shouting out to see if this can be extended to elsewhere, like header photo or anywhere you like!!! Think about it, that anyone who comes to your profile page would see all your nfts stacked everywhere. Isn't that cool?
 
## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- [NFT Avatar branch](https://github.com/dimensiondev/maskbook/tree/lelenei/new-nft-avator)
- [Collectible Plugin in Mask](https://github.com/DimensionDev/Maskbook/tree/develop/packages/maskbook/src/plugins/Collectible)
## Part 3: Contact and Support

@yisiliu for ideas
@guanbinrui for implementation

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 200.0 MASK (1852.0 USD @ $9.26/MASK)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/4294/100026536).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/DimensionDev/Maskbook/4294/100026536).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $4,655,287.20 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 2 months from now.
Please review their action plans below:


**1) [jdevstudios](https://gitcoin.co/jdevstudios) has started work.**

I  have read the guides for the bounty and I'm confident I can produce a profile page for NFT holders. I have over 10 years of development experience.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/4294/100026536).

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 2 months from now.
Please review their action plans below:


**1) [developerfred](https://gitcoin.co/developerfred) has started work.**

I would love to do this integration

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/DimensionDev/Maskbook/4294/100026536).
