### ISSUE TITLE
[Bounty] Integrate CryptoArt.ai, an NFT marketplace, into Mask Network

### ISSUE THREAD

**Issue by tzhan28** [DimensionDev/Maskbook#4311]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [ ] Intermediate
  - [x] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x]  $2000

## Part 1: Problem Description

**Background**
CryptoArt.ai is a marketplace to collect and trade unique, single-edition digital artworks. 

**Solution**
Create a plugin that integrate CryptoArt.ai.  The basic product logic could resemble our Opensea and Rarible integration. The UI is in a card style with different tabs serving different purposes. 
![opensea1](https://user-images.githubusercontent.com/45725943/131393055-857dbd89-f5a5-436f-b9ee-c029b8c17455.gif)
_Opensea Plugin UI_

Default page could be the item overview 
A second tab for detailed info
Other tabs for offerings, historical prices etc.

CryptoArt.ai is more artist focused than Opensea and Rarible. So the UI design could go along the same line.  DO talk to us before committing to certain integration design though. Could stick with the Opensea layout as well.

Any link from CryptoArt.ai on Twitter could trigger the plugin ( could have some slightly different treatment). The tab order can be changed, corresponding landing and ending page could be added. Share button for such a social NFT platform is a must

Language like 
**I just purchased xxx for yyy dollar, and I feel like on top of the world.** 
Could be added to help spread the word.

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- [CryptoArt.ai Github](https://github.com/CryptoArtAi/cryptoart-contracts)

## Part 3: Contact and Support
@yisiliu for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q
CryptoArt.AI discord server: https://discord.com/invite/n94R4haXTF

**Submission Requirements**
Please include demo to show the integration is working.

**Winner Announcement Date**
Winners will be announced at the conclusion of GR11

**Judging Criteria**
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience
