### ISSUE TITLE
[Demand] View NFT tokens in collections

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#4751]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (Web3)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

Add a switch as "View in collections" in the Web3 tab. If the user turns it on, the NFT tokens will be listed in collection groups.
