### ISSUE TITLE
[Demand] Integrate Fortmatic Wallet Provider

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#4778]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

+ [Documentation](https://docs.fortmatic.com/)
+ [ Fortmatic Demo APP](https://demo-kitchen-sink--fortmatic.repl.co/)

## Part 2: Problem to Solve

+ Support Mainnet and BSC chain.

## Part 3: Expected Behavior

+ [ ] Send transaction with Fortmatic.
+ [ ] Sign message with Fortmatic.

**Comment by UncleBill** [comment]
Integrated in https://github.com/DimensionDev/Maskbook/pull/4871

cc @zhouhanseng @guanbinrui
