### ISSUE TITLE
[Bounty] Integrate  Solv; A Decentralized Platform for Creating, Managing, and Trading Financial NFTs into Mask Plugin 

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#4845]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [ ] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  [x] 2 weeks

- Bounty Size
  [x] 150 $MASK or $2000

## Part 1: Problem Description
 
**Background** Solv Protocol is the decentralized platform for creating, managing, and trading Financial NFTs

**Solution** Create a plugin that integrates Solv. The UI is in a buy or create icon 

<img width="849" alt="23D62279-C9CD-41A0-8F76-DEE7DCBC7DF3" src="https://user-images.githubusercontent.com/94482490/142519615-63815eaa-9664-4203-9177-773ada2b51fb.png">

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)

## Part 3: Contact and Support
@yisiliu for ideas @Jack-Works for implementations Mask Network discord server: https://discord.gg/4Xccj7a75Q Taker Telegram server: discord.gg/ewpb9jqzyD
Submission Requirements Please include demo to show the integration is working.
Winner Announcement Date Winners will be announced at the conclusion of GR11
Judging Criteria Have a working demo. Clean code & tech design Clear UI, easy to use and generally good user experience
