### ISSUE TITLE
[Bounty] Integrate Sudoswap A Digital Marketplace With Zero Fees into Mask Plugin 

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#4854]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  [x] 2 weeks

- Bounty Size
  [x] 150 $MASK or $2000

## Part 1: Problem Description
 
**Background**

Sudoswap is a digital marketplace with zero swap fees. Sudoswap is gas-optimized meaning you only pay gas for approved swaps and there is no transaction needed to create an order. Sudoswap is a multi-asset platform, you can trade with any combination of ER20, 720, and 1155. Sudoswap is also non-custodial, assets never leave your wallet until the swap is accepted by both parties. 

**Solution** 
Create a plugin that integrates Sudoswap into Mask. The UI should be identical to other swaps

<img width="538" alt="Screen Shot 2022-01-17 at 5 58 04 PM" src="https://user-images.githubusercontent.com/94482490/150025785-f08776b1-5df3-4c12-9db6-aff5dab7181a.png">

<img width="538" alt="Screen Shot 2022-01-17 at 6 05 07 PM" src="https://user-images.githubusercontent.com/94482490/150025822-ef4cecdd-8ccc-4bd6-b05a-6e78e98c3d2b.png">

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://sudoswap.xyz/#/

## Part 3: Contact and Support
Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Sudo Swap discord server: https://discord.com/invite/47M95tNFwt

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lindayeboah #4854 so that we can find you on Discord. We can create a dedicated group for faster communication once we found each other

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by taylor** [comment]
Wrong taylor

**Comment by yisiliu** [comment]
> Wrong taylor

sorry bro

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 150.0 MASK (1309.5 USD @ $8.73/MASK)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/4854/100027493).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/4854/100027493).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,450,486.09 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 1 week, 4 days from now.
Please review their action plans below:


**1) [gitcoindev](https://gitcoin.co/gitcoindev) has started work.**

SudoSwap integration into MaskBook.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/4854/100027493).

**Comment by developerfred** [comment]
@LindaMask I will work on this

**Comment by memosr** [comment]
sudoswap good
