### ISSUE TITLE
[Bounty] Integrate Enzyme, A Defi Asset Management Tool into Mask Plugin 

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#4858]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [ ] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  [x] 2 weeks

- Bounty Size
  [x] 150 $MASK or $2000

### **Part 1: Problem Description**
**Background** Enzyme is a decentralized asset management infrastructure built on Ethereum. Using Enzyme Smart Vaults, individuals and communities can build, scale and monetize investment (or execution) strategies that employ the newest innovations in decentralized finance.
Previously defi plugins on Mask, like the trading widgets powered by 0x and Uniswap, have been plagued with high ETH gas prices. However, the launch of polygon and BSC integration, has solved most of the problem. Apps that were hindered by monstrous ETH gas prices are much more affordable.
Enzyme is available on eth mainnet.

**Solution** Create a plugin that integrates Enzyme. The UI could resemble Dhedge in a card style with different tabs serving different purposes.
 
Dhedge Plugin UI

<img width="646" alt="Screen Shot 2021-11-19 at 11 30 53 PM" src="https://user-images.githubusercontent.com/94482490/142714424-88f9059a-1907-4e6c-88b5-94e1ddcc8500.png">

_Leader Board_ 

<img width="1227" alt="Screen Shot 2021-11-19 at 10 41 49 PM" src="https://user-images.githubusercontent.com/94482490/142714434-fd6987c9-190b-4c39-866b-ab75c65de4ba.png">

_Deposit page_

<img width="1076" alt="Screen Shot 2021-11-19 at 10 55 36 PM" src="https://user-images.githubusercontent.com/94482490/142714439-5130873d-9f65-469e-aca0-c96183934077.png">

The default page of the UI could be the Leader Board page, including basic information shown on the official website (Suggestion is to port directly). Once a user clicks on the  fund they want to deposit to, the users will be taken to the deposit page to place their deposit directly from their  wallet 
A second tab may be a page where  all my investments are displayed
Any link from Enyzme on Twitter could trigger the plugin ( could have some slightly different treatment). The tab order can be changed, corresponding landing and ending page needs to be added. 
Required Verbiage: I just invested xxx dollars into xxx vault, what will my returns be? This type of language should be included to help spread the word.

**### Part 2: Resources**

**Bounty Guide**

- https://enzyme.finance/
- https://app.enzyme.finance/depositor/leaderboard

### **Part 3: Contact and Support**
@yisiliu for ideas @Jack-Works for implementations Mask Network discord server: https://discord.gg/4Xccj7a75Q Enzyme Finance discord server:http://discord.enzyme.finance
Submission Requirements Please include demo to show the integration is working.
Winner Announcement Date Winners will be announced at the conclusion of Open Defi Hackathon
Judging Criteria Have a working demo. Clean code & tech design Clear UI, easy to use and generally good user experience

**Comment by SebastianLF** [comment]
Can I work on it ?

**Comment by LindaMask** [comment]
@SebastianLF Yes, you can work on it. Are you on telegram or discord?

**Comment by SebastianLF** [comment]
> @SebastianLF Yes, you can work on it. Are you on telegram or discord?

I'm already working on zora integration.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 150.0 MASK (1651.5 USD @ $11.01/MASK)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/4858/100027370).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/4858/100027370).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,323,885.28 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 264 years, 10 months from now.
Please review their action plans below:


**1) [bshevchenko](https://gitcoin.co/bshevchenko) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/dimensiondev/maskbook/4858/100027370?mutate_worker_action=approve&worker=bshevchenko) | [reject worker](https://gitcoin.co/issue/dimensiondev/maskbook/4858/100027370?mutate_worker_action=reject&worker=bshevchenko))_.**

Ready to start with this one! :)
**2) [akumar1503](https://gitcoin.co/akumar1503) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/dimensiondev/maskbook/4858/100027370?mutate_worker_action=approve&worker=akumar1503) | [reject worker](https://gitcoin.co/issue/dimensiondev/maskbook/4858/100027370?mutate_worker_action=reject&worker=akumar1503))_.**

I will integrate the required tabs and feature to connect with Enzyme using it's subgraph, will complete in 2 weeks.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/4858/100027370).

**Comment by akumar1503** [comment]
Hey @LindaMask , I would like to work on this.

I'm thinking of using Enzyme provided subgraph api.

> The default page of the UI could be the Leader Board page, including basic information shown on the official website (Suggestion is to port directly). 

Could you please provide some info on how to port it directly, like do they provide embedded url or something?

**Comment by LindaMask** [comment]
Hi @akumar1503 yes, I can provide some info. Please reach out to me on telegram @Lin_DAO so I can connect you with my team.
