### ISSUE TITLE
[Bounty] Add PancakeSwap to Mask Network

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#4860]
### Catalogue
- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [ ] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  [x] 2 weeks

- Bounty Size
  [x] 150 $MASK or $2000

**Part 1: Problem Description**

**Background** PancakeSwap is a decentralized exchange built on Binance Smart Chain, a fast and inexpensive alternative to Ethereum. Much like the celebrated Uniswap DeFi AMM protocol running on Ethereum, PancakeSwap enables users to swap between cryptocurrency assets by tapping into user-generated liquidity pools.

**Solution** Add PankcakeSwap as a trading provider on Mask
 
### Part 2: Resources

-  [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md
- https://docs.pancakeswap.finance/

### Part 3: Contact and Support

@yisiliu for ideas @Jack-Works for implementations Mask Network discord server: https://discord.gg/4Xccj7a75Q PankcakeSwap discord: https://discord.com/invite/b6HTktu
Submission Requirements Please include demo to show the integration is working.
Winner Announcement Date Winners will be announced at the conclusion of GR11
Judging Criteria Have a working demo. Clean code & tech design Clear UI, easy to use and generally good user experience

**Comment by Tedko** [comment]
<img width="1402" alt="Screen Shot 2021-11-22 at 02 49 56" src="https://user-images.githubusercontent.com/6687437/142775068-4425a447-e540-4f8a-af0c-3bfa565b52a1.png">


It's integrated for months. There's even blog/news about it and you can try the product w/ pancake. 

DYOR b4 post bounty otherwise its just waste of time

**Comment by LindaMask** [comment]
Hi Suji,

Thanks for the feedback.

Taylor provided a spreadsheet to me with the bounties I needed to write.

To resolve this confusion I will connect with him to organize the
spreadsheet. In the spreadsheet it doesn’t indicate that these features
have already been integrated.

They are listed as “coming soon” in the spreadsheet, I will connect with
Taylor so there aren’t any duplicated efforts.

Below is the link of the spreadsheet for your reference


https://docs.google.com/spreadsheets/d/1z50WR4uHOYcfirtUQy59LVmRF74XxpZVdOurLqq5c1g/edit#gid=276863344

**Comment by Tedko** [comment]
@LindaMask regardless of the sheet you need to try product and do basic check of source code on GitHub and then can easily lead you to the needed area. 
I suppose you have all these needed skills.

**Comment by LindaMask** [comment]
Thanks for the feedback. Will work on this.
