### ISSUE TITLE
[Bounty] Integrate CELO into Mask 

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#4866]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  [x] 2 weeks

- Bounty Size
  [x] $2000

### Part 1: Problem Description

**Background** Celo (CGLD) is an open-sourced Proof-of-Stake (PoS) blockchain designed to support stablecoins and tokenized assets with an algorithmic reserve-backed stability mechanism. CGLD is a cryptocurrency that acts as a utility and governance token for the CGLD) platform.

**Solution** As the first step of our cooperation, we, Mask Network, would like to integrate Celo as one of our default supported blockchain system in our internal Mask Wallet, so that further on-chain interactions would happen directly within Mask Network without leaving the platform. We believe this would further help us attract more users from different projects, aiming at different goals to maximize users experiences in the broad blockchain world.

If you are interested in this bounty, please make sure that you contact us first to see how our structure looks like and proceed to the development afterwards.

### Part 2: Resources

- https://celo.org/
- https://github.com/DimensionDev/Maskbook/tree/master/packages/maskbook/src/plugins/Wallet

### Part 3: Contact and Support

@yisiliu for ideas @Jack-Works for implementations Mask Network discord server: https://discord.gg/4Xccj7a75Q Celo discord server: https://t.me/celoplatform

**Comment by Tedko** [comment]
@LindaMask u need knowledge of whether this chain is evm compatible L1/L2 (Bsc, polygon, xdai or here Celo) or a different designed L1 like Flow / Solana. 

Always try use the chain and it's wallet b4 posting bounties

**Comment by Tedko** [comment]
And FYI the difficulty level of different chains integration is different. Evm compatible ones are relatively easy though

**Comment by LindaMask** [comment]
Thanks Suji, appreciate the feedback.

**Comment by brymut** [comment]
Hi @LindaMask, made an attempt at this. Could someone please check the progress?

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 2000.0 DAI (2000.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/4866/100027366).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/4866/100027366).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,310,031.78 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 264 years, 11 months from now.
Please review their action plans below:


**1) [brymut](https://gitcoin.co/brymut) has been approved to start work.**

Include necessary changes to integrate Celo chain into Mask plugin and implement feedback from Mask team

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/4866/100027366).

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 2000.0 DAI (2000.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@brymut](https://gitcoin.co/brymut)



@yisiliu please take a look at the submitted work:
* [PR](https://github.com/DimensionDev/Maskbook/pull/5052) by @brymut

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/4866/100027366)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/4866/100027366).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,413,407.62 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
