### ISSUE TITLE
[Bounty] Add IPFS as Another Provider for The File Service into Mask 

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5021]
## Catalogue

- [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner 
  - [ ] Intermediate
  - [x] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 1000 USD

### Part 1: Problem Description

**Background** The InterPlanetary File System (IPFS)  is a protocol and peer-to-peer network for storing and sharing data in a distributed file system. IPFS uses content-addressing to uniquely identify each file in a global namespace connecting all computing devices

**Solution** We have already integrated Arweave as the provider of our file service, by which users can upload any type of file and attach it to a social network post. To extend this capability and provide more options for our users, we would like to add more providers such as IPFS. You might need to figure out how to create a micro-service to help pay for user's storage fees just like what we did with Arweave. Official help from IPFSteam can be directly linked in this bounty.

### Part 2: Resources
- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://ipfs.io/

  
### Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
IPFS Github: https://github.com/ipfs

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lindayeboah #5021 so that we can find you on Discord. We can create a dedicated group for faster communication once we found each other

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience
