### ISSUE TITLE
[Bounty] Add Sudo Swap into Mask Plugin

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5025]
## Catalogue

- Platform
  - [ ] Gitcoin
  - [ ] Hackerlink
  - [x] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [ ] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 2000 USD

### Part 1: Problem Description

**Background** Sudo Swap digital marketplace with zero fees | powerful NFT liquidity primitives

**Solution** Integrate Sudo Swap into Mask.

For UI design, Once the NFT icon on the entry page (screenshot below) is triggered the next page should have an icon lst of the swap  they would like to trade with, in this case Sudo swap should be one of the swap  icons. 

Once Sudo Swap is selected there should be a display of all NFTs in the user’s wallet.
Once the desired NFT is selected, the user should be prompted to a page similar to the Swap page (screenshot below)  

There should be a confirm button to confirm that the user has initiated the swap. 
A third tab should also be created showing the transaction history of all NFT swaps the user has initiated, this transaction should display the status of the swap and should read, “pending”(the wallet address you are looking to swap with has not accepted or rejected the swap) “accepted” (the wallet address you are looking to swap with has accepted the swap)”rejected” (the wallet address you are looking to swap with has rejected the swap) Reference images below for UI ideas

_Mask Entry Page_

<img width="543" alt="Screen Shot 2021-12-01 at 11 43 26 AM" src="https://user-images.githubusercontent.com/94482490/144301580-c480ab2f-b331-42fa-97c1-0047a17c8d18.png">

_Sudo Swap Create Swap Page_

<img width="554" alt="Screen Shot 2021-12-01 at 2 28 55 PM" src="https://user-images.githubusercontent.com/94482490/144300827-4a2367f0-bdb9-422d-8e21-b8cf82c8c91d.png">

_Sudo Swap Deposit Page_

<img width="554" alt="Screen Shot 2021-12-01 at 2 29 10 PM" src="https://user-images.githubusercontent.com/94482490/144300968-521f24a6-1fbb-41fb-ba61-caba73ed8372.png">

Any link from Sudo Swap on Twitter could trigger the plugin ( could have some slightly different treatment). Share button for such a social NFT platform is a must

Required verbiage "I just traded xxx for yyy using Mask Network Plugin" should be added to help spread the word.

### Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://sudoswap.xyz/#/

 
### Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Sudo Swap discord server: https://discord.com/invite/47M95tNFwt

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lindayeboah #5025 so that we can find you on Discord. We can create a dedicated group for faster communication once we found each other

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 150.0 MASK (1845.0 USD @ $12.3/MASK)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5025/100027245).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/5025/100027245).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,981,465.26 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by shawnWeb3** [comment]
I'd like to work on this, Is this bounty still valid?  @yisiliu @tzhan28 @LindaMask

**Comment by LindaMask** [comment]
Hey @shawnWeb3 yes it is still valid. You can work on it

**Comment by gitcoindev** [comment]
I started this bounty via Gitcoin, did not realize it was already taken. I will stop there and pick another one.

**Comment by qqqzhch** [comment]
I haven't found Sudo Swap inside the product yet, I'll look into this task.
