### ISSUE TITLE
[Bounty] Add Swarm as Another Provider for The File Service into Mask

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5027]
## Catalogue

- Platform
  - [ ] Gitcoin
  - [ ] Hackerlink
  - [x] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [ ] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 1000 USD

### Part 1: Problem Description

**Background**  Swarm is a system of peer-to-peer networked nodes that create a decentralized storage and communication service. The system is economically self-sustaining due to a built-in incentive system enforced through smart contracts on the Ethereum blockchain

**Solution** We have already integrated Arweave as the provider of our file service, by which users can upload any type of file and attach it to a social network post. To extend this capability and provide more options for our users, we would like to add more providers such as Swarm. You might need to figure out how to create a micro-service to help pay for user's storage fees just like what we did with Arweave. Official help from Steam can be directly linked in this bounty.

### Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://www.ethswarm.org/

 
### Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Swarm discord server: https://discord.com/invite/GU22h2utj6

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lindayeboah #### so that we can find you on Discord. We can create a dedicated group for faster communication once we found each other

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 1000.0 USDC (1000.0 USD @ $1.0/USDC)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5027/100027246).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/5027/100027246).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,982,465.26 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by yisiliu** [comment]
@xiazhiming we need an update on the design so that we could support users to choose different providers while they are using our file service, both on the front end and in the dashboard.

**Comment by lljxx1** [comment]
@yisiliu @LindaMask 
Plan to add two providers for File Service:
- Swarm
- IPFS

![image](https://user-images.githubusercontent.com/7993835/145983822-b9da183f-8b01-4858-9922-bacc6d7017a7.png)
https://github.com/DimensionDev/Maskbook/issues/5021

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 1000.0 USDC (1000.00 USD @ $1.0/USDC) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5027/100027246)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/5027/100027246).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $5,347,586.28 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by LindaMask** [comment]
@lljxx1 This design looks good to us, please proceed.

**Comment by lljxx1** [comment]
@LindaMask https://github.com/DimensionDev/Maskbook/pull/5195
Waiting for review

**Comment by LindaMask** [comment]
@lljxx1 Hi Yes, thanks for the update. I will get back to you once the review has been concluded
