### ISSUE TITLE
[Bounty] Integrate Trader xyz into Mask Plugin

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5028]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 2000 USD

### Part 1: Problem Description

**Background** Tader is an Ox project that lets you quickly and safely trade NFTs.

**Solution** Build Trader xyz into Mask.

For UI design, Once NFT icon on the entry page (screenshot below) is triggered the next page should have an icon list of the swap they would like to trade with, in this case, Trader should be one of the swap icons.

Once Trader is selected there should be a display of all NFTs in the user’s wallet.

Once the Trade icon is triggered the next page can be similar to the  “sell” page, users should be able to pick the NFTs they would like to sell  from their wallet. 

After NFTs are traded, a unique sharable trade link should be generated that the users can tweet/send out to people they would like to trade with.
 
 
_The Entry Page_

<img width="543" alt="Screen Shot 2021-12-01 at 11 43 26 AM" src="https://user-images.githubusercontent.com/94482490/144310110-c0b38975-5f98-4f98-b626-c8263da12f83.png">
 
 
_Trader Sell Page_

<img width="554" alt="Screen Shot 2021-12-01 at 3 38 20 PM" src="https://user-images.githubusercontent.com/94482490/144310315-1d1aa242-f785-41ea-ac6a-cfa134d86aac.png">

Any link from Trader xyz on Twitter could trigger the plugin ( could have some slightly different treatment). 

Share button for such a social NFT platform is a must
Required verbiage: "I just traded xxx nft for yyy eth, using Mask Network Plugin"  should be added to help spread the word.

### Part 3: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://trader.xyz/

 
Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Trader discord server: https://discord.com/invite/GHZceZhbZU

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lindayeboah #5023 so that we can find you on Discord. We can create a dedicated group for faster communication once we found each other

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 150.0 MASK (1845.0 USD @ $12.3/MASK)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5028/100027247).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/5028/100027247).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,984,310.26 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by vaimeo** [comment]
Hi i want to work for this bounty, but there is one bug

**Comment by tzhan28** [comment]
What bug？

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 8 hours from now.
Please review their action plans below:


**1) [vaimeo](https://gitcoin.co/vaimeo) has started work.**

I am going to build the project as required.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5028/100027247).

**Comment by SebastianLF** [comment]
@yisiliu Link generated should be of type "https://trader.xyz/t/swift-future-yak" ? I asked devs there and they say that there's no way to generate this kind of url outside their UI.

**Comment by LindaMask** [comment]
closed
