### ISSUE TITLE
[Bounty] Integrate OpenOcean, a multi-chain CEX/DEX aggregator into Mask Plugin

### ISSUE THREAD

**Issue by caojin13** [DimensionDev/Maskbook#5107]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [x] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 150 $MASK

## Part 1: Problem Description

**Background**
OpenOcean is the world’s first full aggregation protocol for crypto trading that sources liquidity from DeFi and CeFi markets and enables cross-chain swaps (across Ethereum, Ethereum Layer2 such as Loopring and Polygon, Binance Smart Chain, Solana, Avalanche, Fantom, OEC, HECO, Ontology, TRON). Their intelligent routing algorithm finds the best prices from DEXes and CEXes and splits the routes to provide traders with the best prices with low slippage and fast settlement. OpenOcean provides an API and arbitrage tools for users to operate automated arbitrage strategies.

Mask Network has been seeking to provide more trading/swapping options for users, especially with trading protocols that provide multi-chain solutions. 

**Solution**
Please condense the OpenOcean pool & trading info into the existing design. 
- Integrate OpenOcean under the savings button on the entry page
- Create a plugin that integrates OpenOcean Swap features

See our mock design [here](https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/TwitterV1?node-id=17600%3A374185), does not need to be 1-to-1 but should follow the flow.

The UI for the swap plugin should be identical to other swaps
(On Polygon)
![On Polygon](https://s3.bmp.ovh/imgs/2021/12/6db0a05df34837ef.png)

(On Ethereum mainnet)
![On Ethereum mainnet](https://s3.bmp.ovh/imgs/2021/12/6a0e38c0b0ef9c1a.png)

Any link cashtag with viable ticker, like $ETH on Twitter, could trigger the plugin. Swaps are also accessible via top line search bar and the swap entry on the left bar menu.

If you have ideas that might make more sense, please talk to us.

Required verbiage to help spread the word: “I just swapped xxx $[tokenname] into $[tokenname] with OpenOcean @OpenOceanGlobal on Mask extension @realMaskNetwork”

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- [OpenOcean](https://openocean.finance/)

## Part 3: Contact and Support
@LindaMask for ideas
@guanbinrui for implementations

Mask Network discord server: https://discord.gg/4Xccj7a75Q
OpenOcean discord server: https://discord.gg/cxK6CCYcGp 

Please speak up in the Mask discord's bounty section, so that we can find you on Discord. We can create a dedicated group for faster communication once we found each other

## Submission Requirements
Please include demo to show the integration is working.

## Judging Criteria
- Have a working demo
- Clean code & tech design
- Clear UI, easy to use, and generally good user experience

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 150.0 MASK (1911.0 USD @ $12.74/MASK)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5107/100027288).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/5107/100027288).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $5,713,788.23 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 264 years, 11 months from now.
Please review their action plans below:


**1) [developerfred](https://gitcoin.co/developerfred) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/dimensiondev/maskbook/5107/100027288?mutate_worker_action=approve&worker=developerfred) | [reject worker](https://gitcoin.co/issue/dimensiondev/maskbook/5107/100027288?mutate_worker_action=reject&worker=developerfred))_.**

I am interested in adding this aggregator.
**2) [harjaapdhillon16](https://gitcoin.co/harjaapdhillon16) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/dimensiondev/maskbook/5107/100027288?mutate_worker_action=approve&worker=harjaapdhillon16) | [reject worker](https://gitcoin.co/issue/dimensiondev/maskbook/5107/100027288?mutate_worker_action=reject&worker=harjaapdhillon16))_.**

I would just start understanding the react patterns used in the project and develop features according to that

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5107/100027288).

**Comment by harjaapdhillon16** [comment]
@LindaMask can you help me out and provide me more details about this task !

**Comment by LindaMask** [comment]
@harjaapdhillon16 sure, what would you like to know? Reach out to me on telegram Lin_DAO
