### ISSUE TITLE
[Bounty] Add CyberConnect plugin for Mask

### ISSUE THREAD

**Issue by sThReal** [DimensionDev/Maskbook#5148]
## Catalogue

- Platform
  - [ ] Gitcoin
  - [ ] Hackerlink
  - [x] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] *PLACEHOLDER*
- Bounty Size
  - [x] *PLACEHOLDER*

## Part 1: Problem Description
Add the CyberConnect plugin for mask 
## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)

## Part 3: Contact and Support
sean.zhao@cybertinolab.com sean(dev)
spadequeen7@gmail.com. shiyu(Boss)
