### ISSUE TITLE
[Bounty]  Integrate Attrace a Referral Protocol, into Mask Plugin

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5444]
## Catalogue

- Platform
  - [ ] Gitcoin
  - [ ] Hackerlink
  - [x] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 150 $MASK or $2000 USD

## Part 1: Problem Description

**Background** Attarce is a Referral Protocol for crypto assets where anyone can sign up and promote. Attrace facilitates blockchain referrals by connecting Project, Promoters, and Participate in the web 3 economy. 

The referral is a reward/bounty deposited by a crypto project to smart contract on Attrace Referral Network. The reward/bounty is intended to incentivize the promotion of an NFT Drop, IDO participation or Liquidity Pool provision. The moment the referral is set up by the project it is made available for promoters to sign up for promotion via Referral App.
These referrals are considered decentralized because not a single party is in control nor can it influence verification of referral conversions and bounties. Attrace Referral App is built on top of Attrace Referral Network which is utilizing Verifier Nodes to verify the conversion and entitle a bounty to a promoter and participant once the successful referral is observed
 
 
**Solution** Create a plugin that integrates Attrace into Mask Plugin. Please reference the below wireframe and link below for the **complete** UI design 

https://www.figma.com/file/dOowOC5qEjZQQr4onHRR14/Attrace-%3C%3E-Mask-(Integration-and-Design)?node-id=0%3A1
 
_Project_
<img width="426" alt="Screen Shot 2022-01-13 at 1 20 40 PM" src="https://user-images.githubusercontent.com/94482490/149388127-45f19eae-9577-4b5d-ab7e-282d332354be.png">

<img width="433" alt="Screen Shot 2022-01-13 at 1 21 07 PM" src="https://user-images.githubusercontent.com/94482490/149388139-e90ffadf-76a7-4f3c-8744-d4bc3ba212ae.png">

<img width="433" alt="Screen Shot 2022-01-13 at 1 21 22 PM" src="https://user-images.githubusercontent.com/94482490/149388149-f7f2cada-7050-493d-aa4c-a0625d0b790e.png">

<img width="433" alt="Screen Shot 2022-01-13 at 1 21 36 PM" src="https://user-images.githubusercontent.com/94482490/149388184-f280ee05-8068-4266-9795-8d82041fc9f2.png">

<img width="433" alt="Screen Shot 2022-01-13 at 1 21 59 PM" src="https://user-images.githubusercontent.com/94482490/149388197-a018339d-3d93-44be-9f6f-a7f9ffe15558.png">

<img width="287" alt="Screen Shot 2022-01-13 at 1 22 35 PM" src="https://user-images.githubusercontent.com/94482490/149388214-b08ee364-538c-422b-b1b2-859a8bb4e1ae.png">

<img width="287" alt="Screen Shot 2022-01-13 at 1 22 51 PM" src="https://user-images.githubusercontent.com/94482490/149388242-aae72d94-99cb-4061-afda-d353cc5f1d9b.png">

<img width="320" alt="Screen Shot 2022-01-13 at 1 23 13 PM" src="https://user-images.githubusercontent.com/94482490/149388254-05c61c35-103f-42ac-8b9c-e57baaa7a793.png">

<img width="580" alt="Screen Shot 2022-01-13 at 1 26 49 PM" src="https://user-images.githubusercontent.com/94482490/149388272-5a83a4e8-24c6-4ab4-9b48-67564fe07343.png">

<img width="580" alt="Screen Shot 2022-01-13 at 1 27 43 PM" src="https://user-images.githubusercontent.com/94482490/149388296-67501a23-c3c7-4bbf-aafe-fdf41cf63803.png">

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://attrace.com/

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Attrace discord server: https://discord.com/invite/WSX2RufvbV
Telegram: Lin_DAO (for fastest response)

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lin_dao #5444 so that we can find you on Discord. We can create a dedicated group for faster communication once we found each other. 

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by LindaMask** [comment]
@dhruvjain1122 is working on this bounty

**Comment by f8al3rr** [comment]
hi! is this still open / is someone still working on this? i'd be interested to complete this
