### ISSUE TITLE
[Bounty] Integrate Dexalot, a Decentralized Exchange into Mask Plugin

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5471]
## Catalogue

- Platform
  - [ ] Gitcoin
  - [ ] Hackerlink
  - [x] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 150 $Mask or 2000 USD 

## Part 1: Problem Description

**Background** 
Dexalot is an exchange aiming at bringing the traditional centralized exchange user experience without compromising on decentralization and transparency. As such Dexalot implements an on-chain Central Limit Order Book for its trade pairs on the Avalanche platform.  Dexalot allows for users to trade ERC20 tokens supported on the C-chain against the blockchain native currency AVAX. Users can also trade supported ERC20 tokens against other supported ERC20 token.

Dexalot has three differentiating characteristics that set it apart from other centralized and decentralized exchanges:

- Ability to place limit orders full on-chain
Traders can set the size and limit price for their orders. If an order matches an existing order in the order book in terms of price, it removes liquidity (taker order) and executes immediately. If there are no immediate matches in the order book, the order will be added to the order book as a new maker order. Taker orders do not have to be all-or-nothing (AON) as Dexalot supports partially filled orders where the unfilled portion of an order automatically enters the order book as a maker order. Dexalot supports market orders as well but this functionality will be turned on for trade pairs individually that reach appropriate liquidity levels.
Inclusion of users through governance
Dexalot will implement a governance model as well as create incentives for its loyal users in the near future. A strong community ownership and participation in governance is an important goal for the project.
- Built on Avalanche
- Dexalot chose the Avalanche platform for its obvious advantages in speed, throughput and near-instantaneous finality. Previous attempts to bring Central Limit Order Book Functionality on blockchains with inferior consensus protocols typically led to limited adoption, high slippage and large amounts of market risk for the users. Dexalot solves these problems by operating on the C-Chain and it will also look to further improve usability and user experience by potentially moving the technology to a subnet after key platform updates and adequate adoption.

**Solution** 
Create a plugin that integrates Dexalot into Mask. The UI should be identical to other swaps

<img width="538" alt="Screen Shot 2022-01-17 at 5 58 04 PM" src="https://user-images.githubusercontent.com/94482490/149859019-dc9d9c4c-3ad7-4a61-8532-f3a5d23fac44.png">

<img width="538" alt="Screen Shot 2022-01-17 at 6 05 07 PM" src="https://user-images.githubusercontent.com/94482490/149859040-c581ac4b-dafb-4ae1-93ea-e2cb45927b87.png">

See the existing polygon swaps and ETH swaps.

Any link cashtag with a viable ticker, like $ETH on Twitter should trigger the plugin.

Suggested Verbiage
I just swapped $aa worth of xxx token for yyy token, using Mask Plugin. Will I make money?

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://app.dexalot.com/

## Part 3: Contact and Support

@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Dexalot discord server: https://discord.com/invite/dexalot

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lin_dao #5471 so that we can find you on Discord. You can also reach out to lin_DAO on telegram and she will create a dedicated group for faster communication

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 150.0 ETH (474785.73 USD @ $3165.24/ETH)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5471/100027495).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/5471/100027495).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,926,581.32 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by yisiliu** [comment]
@LindaMask what why
