### ISSUE TITLE
[Bounty] Integrate Saber, a Decentralized Exchange into Mask Plugin

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5473]
## Catalogue

- Platform
  - [ ] Gitcoin
  - [ ] Hackerlink
  - [x] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 100 $Mask or 1000 USD

## Part 1: Problem Description

**Background**

Saber is a decentralized exchange (DeX) focused on stablecoin swapping and staking. Built on the Solana platform, Saber currently offers swapping opportunities for about 30 cryptocurrencies.

Users can also stake funds in liquidity pools. Saber currently operates 25 liquidity pools, each of which represents a swap pair (e.g. USDT-USDC), and liquidity providers can earn yield based on each swap transaction on the platform involving the pair.

Saber’s key advantage is low transaction fees, low slippage rates, and fast execution times. These advantages are achieved thanks to the app’s native blockchain, Solana, which boasts a much greater throughput and lower transaction costs compared to Ethereum

**Solution**

Create a plugin that integrates Saber into Mask. The UI should be identical to other swaps

<img width="538" alt="Screen Shot 2022-01-17 at 5 58 04 PM" src="https://user-images.githubusercontent.com/94482490/149863743-11548737-20bd-4a8f-a872-b30e867f0b55.png">

<img width="538" alt="Screen Shot 2022-01-17 at 6 05 07 PM" src="https://user-images.githubusercontent.com/94482490/149863761-c5f0854e-89cd-4ce3-9148-b1fb7dfc4dec.png">

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://app.saber.so/#/swap

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Saber discord server: https://discord.com/invite/9buKA9E5Nm

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lin_dao #5473 so that we can find you on Discord. You can also reach out to lin_DAO on telegram and she will create a dedicated group for faster communication

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 150.0 MASK (1309.5 USD @ $8.73/MASK)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5473/100027496).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/5473/100027496).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,927,890.82 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by LindaMask** [comment]
@DhruvJain1122 is working on this
