### ISSUE TITLE
[Bounty] Integrate BenQi, a Non-Costodial Liquidity Market Pool into Mask Plugin 

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5476]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 150 $Mask 2000 USD 

## Part 1: Problem Description
**Background**

BENQI is a non-custodial liquidity market protocol, built on Avalanche. The protocol enables users to effortlessly lend, borrow, and earn interest with their digital assets. Depositors providing liquidity to the protocol may earn passive income, while borrowers are able to borrow in an over-collateralized manner.

**Solution**
Integrate BenQi under the savings button in the entry page.
The savings page will list all savings options provided by AAVE, Compound, YFI ,etc and include both stablecoin savings and non-stable token savings (staking/farming etc).

See our mock design in the link, does not need to be 1 to 1 but should follow the flow
https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/TwitterV1?node-id=17600%3A374185

_The Entry Page_
<img width="543" alt="Screen Shot 2021-12-01 at 11 43 26 AM" src="https://user-images.githubusercontent.com/94482490/149873723-78dc0b7b-4dad-416c-8f55-c1bbcf0889be.png">

_The Savings Page_
<img width="447" alt="Screen Shot 2021-12-01 at 4 53 51 PM" src="https://user-images.githubusercontent.com/94482490/149873778-b6c9248f-719a-482b-9ee9-d2adc9e01c83.png">

_The Supply Page_ 

<img width="466" alt="Screen Shot 2021-12-01 at 11 44 58 AM" src="https://user-images.githubusercontent.com/94482490/149873851-ceca4f49-9819-46c0-babb-6858f89d208e.png">

_BenQi Supply Page_
<img width="999" alt="Screen Shot 2022-01-18 at 12 09 57 AM" src="https://user-images.githubusercontent.com/94482490/149874547-b7d60572-6f8c-4a07-864d-03242f7d6c16.png">

Please condense the BenQi pool info into the existing design. If you have ideas that might make more sense, talk to us.

Required Verbiage to help spread the word: "I just deposited xxx dollars into xxx. Will I make money this week?"

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://benqi.fi/

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
BenQi discord server: https://discord.com/invite/jyPAjZjwk6

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lin_dao #5476 so that we can find you on Discord. You can also reach out to lin_DAO on telegram and she will create a dedicated group for faster communication

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 150.0 MASK (1309.5 USD @ $8.73/MASK)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5476/100027499).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/5476/100027499).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,931,819.32 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 1000.0 USDC (1000.0 USD @ $1.0/USDC)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5476/100028473).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/5476/100028473).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $4,187,346.33 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 1000.0 USDC (1000.0 USD @ $1.0/USDC)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5476/100028472).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/5476/100028472).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $4,187,346.33 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 2 weeks, 2 days from now.
Please review their action plans below:


**1) [lljxx1](https://gitcoin.co/lljxx1) has been approved to start work.**

Integrate BenQi, A Non-Costodial Liquidity Market Pool Into Mask Plugin

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5476/100028472).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 2000.0 USDC (2000.0 USD @ $1.0/USDC) has been submitted by__:

 1. [@lljxx1](https://gitcoin.co/lljxx1)



@lindamask please take a look at the submitted work:
* [PR](https://github.com/DimensionDev/Maskbook/pull/5963) by @lljxx1

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5476/100028472)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/5476/100028472).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $5,041,466.23 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
