### ISSUE TITLE
[Bounty] Integrate Ubeswap, an AMM Protocol for Celo Assets into Mask Plugin

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5824]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 1000 USDC of $MASK equivalent 

## Part 1: Problem Description
**Background** Ubeswap is a decentralized exchange and automated market maker protocol for Celo assets.
Ubeswap is based on elements from Uniswap, Sushiswap, Synthetix, and Compound. This is to ensure that the Ubeswap ecosystem can support as many existing tools and projects from the Ethereum ecosystem as possible.

Ubeswap's goal is to increase liquidity on Celo. We envision a world where anyone can trade any asset from their phone or browser, without having to rely on decades-old clearinghouse technology or other centralized systems. This is only possible if people can invest in good assets. Ubeswap seeks to bring in liquidity from all of DeFi by harnessing the fast transaction times, high block gas limit, and stablecoin system of Celo.

**Solution**  Create a plugin that integrates Ubeswap into Mask. The UI should be identical to other swaps.

![image](https://user-images.githubusercontent.com/94482490/157130011-906d84f3-4abb-439f-a015-fdb0b451c943.png)

![image](https://user-images.githubusercontent.com/94482490/157130041-d4c42347-b1d0-4024-84f0-1e3891b6fc81.png)

_Ubeswap Page_ 

<img width="501" alt="Screen Shot 2022-03-07 at 5 42 05 PM" src="https://user-images.githubusercontent.com/94482490/157130369-5551b0e4-0613-4d94-bd66-9da6b834496c.png">

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://ubeswap.org/
- https://docs.ubeswap.org/

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Ubeswap Discord: https://discord.com/invite/zZkUXCMPGP

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lin_dao #5824  so that we can find you on Discord. For faster communication reach out to lin_DAO on telegram and she will create a dedicated group with the Mask team to start the bounty process

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 6 days, 2 hours from now.
Please review their action plans below:


**1) [dhruvjain1122](https://gitcoin.co/dhruvjain1122) has been approved to start work.**

Ubeswap integration in mask

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5824/100028515).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 1000.0 USDC (1000.0 USD @ $1.0/USDC) has been submitted by__:

 1. [@dhruvjain1122](https://gitcoin.co/dhruvjain1122)



@lindamask please take a look at the submitted work:
* [PR](https://github.com/DimensionDev/Maskbook/pull/5846) by @dhruvjain1122

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5824/100028515)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/5824/100028515).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $4,604,865.17 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
