### ISSUE TITLE
[Bounty] Integrate Beamswap, A DEX Providing Liquidity and Peer to Peer Transactions, into Mask Plugin 

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5827]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks 
- Bounty Size
  - [x] 1000 USDC 

## Part 1: Problem Description
**Background**  
Beamswap is a decentralized exchange (DEX) with an automated market maker (AMM), providing liquidity and peer-to-peer transactions. But it aims to be so much more than that. Supporting an array of services and features, it will allow you to swap crypto assets, both fungible and non-fungible, earn passive income from staking and yield farming, and even launch your own crypto projects on Moonbeam.

**Solution** Create a plugin that integrates BeamSwap into Mask. The UI should be identical to other swaps.

![image](https://user-images.githubusercontent.com/94482490/157136991-f13fab14-c617-4ff7-9589-73371f5314b0.png)

![image](https://user-images.githubusercontent.com/94482490/157137016-36d441ad-ad71-4c7c-84ba-05493626db23.png)

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://beamswap.io/
- https://docs.beamswap.io/
- https://github.com/BeamSwap

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Beamswap Discord: https://discord.com/invite/XRpPFHqJ

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lin_dao #5827 so that we can find you on Discord. For faster communication, reach out to lin_DAO on telegram, and she will create a dedicated group with the Mask team to start the bounty process.

Submission Requirements
Please include a demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by developerfred** [comment]
I'll take this one.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 3 weeks from now.
Please review their action plans below:


**1) [developerfred](https://gitcoin.co/developerfred) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/dimensiondev/maskbook/5827/100028521?mutate_worker_action=approve&worker=developerfred) | [reject worker](https://gitcoin.co/issue/dimensiondev/maskbook/5827/100028521?mutate_worker_action=reject&worker=developerfred))_.**

Integrate beamswap on maskbook

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5827/100028521).
