### ISSUE TITLE
[Bounty] Integrate Harmony, an L2 blockchain built on Ethereum, into Mask 

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5832]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [ ] Intermediate
  - [x] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] 2000 USDC or $MASK equivalent

## Part 1: Problem Description
**Background** Harmony is an open and fast blockchain, featuring a mainnet that runs on an Ethereum network with 2-second transaction finality and 1000 times lower fees than Ethereum.

Harmony (ONE) blockchain is an L2 blockchain platform built on [the Ethereum network](https://cointelegraph.com/ethereum-for-beginners/history-of-eth-the-rise-of-the-ethereum-blockchain), making it easier for developers to create [decentralized apps (DApps)](https://cointelegraph.com/defi-101/what-are-dapps-everything-there-is-to-know-about-decentralized-applications).

**Solution** As the first step of our cooperation, we, Mask Network, would like to integrate Harmony as one of our default supported blockchain system in our internal Mask Wallet, so that further on-chain interactions would happen directly within Mask Network without leaving the platform. We believe this would further help us attract more users from different projects, aiming at different goals to maximize users experiences in the broad blockchain world.

If you are interested in this bounty, please make sure that you contact us first to see how our structure looks like before development.

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://www.harmony.one/
- https://github.com/harmony-one/docs-home
- https://docs.harmony.one/home/

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Harmony Discord: https://discord.com/invite/rdCmBpe

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lin_dao #5832  so that we can find you on Discord. For faster communication reach out to lin_DAO on telegram and she will create a dedicated group with the Mask team to start the bounty process

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by developerfred** [comment]
Thanks 👌 @LindaMask

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 3 weeks, 1 day from now.
Please review their action plans below:


**1) [developerfred](https://gitcoin.co/developerfred) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/dimensiondev/maskbook/5832/100028528?mutate_worker_action=approve&worker=developerfred) | [reject worker](https://gitcoin.co/issue/dimensiondev/maskbook/5832/100028528?mutate_worker_action=reject&worker=developerfred))_.**

Integration Network Harmony One on Maskbook portal

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5832/100028528).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 1 week, 6 days from now.
Please review their action plans below:


**1) [developerfred](https://gitcoin.co/developerfred) has been approved to start work.**

Add Harmony Network on MaskBook
**2) [anish-mukherjee](https://gitcoin.co/anish-mukherjee) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/dimensiondev/maskbook/5832/100028527?mutate_worker_action=approve&worker=anish-mukherjee) | [reject worker](https://gitcoin.co/issue/dimensiondev/maskbook/5832/100028527?mutate_worker_action=reject&worker=anish-mukherjee))_.**

A plugin to integrate Harmony into Mask

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5832/100028527).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 2000.0 USDC (2000.0 USD @ $1.0/USDC) has been submitted by__:

 1. [@developerfred](https://gitcoin.co/developerfred)



@lindamask please take a look at the submitted work:
* [PR](https://github.com/DimensionDev/Maskbook/pull/5835) by @developerfred

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5832/100028527)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/dimensiondev/maskbook/5832/100028527).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $4,615,136.10 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
