### ISSUE TITLE
[Bounty] Integrate Terra, A Layer-1 Blockchain Protocol into Mask Plugin

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5836]
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [ ] Intermediate
  - [x] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 3 weeks 
- Bounty Size
  - [x] 3000 USDC or $MASK equivalent

## Part 1: Problem Description
**Background**  Terra is a layer-1 blockchain protocol with smart-contract functionality that works as a payments-focused fintech ecosystem leveraging algorithmic stablecoins, the stability of whose value is maintained by internal algorithms.  

**Terra** aims to build a global payment network backed by a price-stable currency and propelled by its blockchain payment solution, with the goal of becoming a more affordable and efficient alternative to e-commerce payment rails

Terra operates with a delegated proof of stake consensus algorithm and is a Tendermint based Layer 1 protocol, built using Cosmos-SDK. It is considered a part of the Cosmos ecosystem.

**Solution** As the first step of our cooperation, we, Mask Network, would like to integrate Terra as one of our default supported blockchain system in our internal Mask Wallet, so that further on-chain interactions would happen directly within Mask Network without leaving the platform. We believe this would further help us attract more users from different projects, aiming at different goals to maximize users experiences in the broad blockchain world.

If you are interested in this bounty, please make sure that you contact us first to see how our structure looks like before development.

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- https://github.com/terra-money/
- https://docs.terra.money/

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Terra Telegram: https://t.me/TerraLunaChat

Please speak up in the Mask discord's bounty section or just discord dm @yisiliu or @taylor zhang or @lin_dao #5836  so that we can find you on Discord. For faster communication reach out to lin_DAO on telegram and she will create a dedicated group with the Mask team to start the bounty process

Submission Requirements
Please include demo to show the integration is working.

Judging Criteria
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 3 weeks from now.
Please review their action plans below:


**1) [developerfred](https://gitcoin.co/developerfred) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/dimensiondev/maskbook/5836/100028537?mutate_worker_action=approve&worker=developerfred) | [reject worker](https://gitcoin.co/issue/dimensiondev/maskbook/5836/100028537?mutate_worker_action=reject&worker=developerfred))_.**

Terra blockchain on maskbook

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5836/100028537).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 1 day, 16 hours ago.
Please review their action plans below:


**1) [richikchanda1999](https://gitcoin.co/richikchanda1999) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/dimensiondev/maskbook/5836/100028537?mutate_worker_action=approve&worker=richikchanda1999) | [reject worker](https://gitcoin.co/issue/dimensiondev/maskbook/5836/100028537?mutate_worker_action=reject&worker=richikchanda1999))_.**

I will go through the codebase on Github
Check out the way in which other chains have been added
Integrate Terra
**2) [0xpyk](https://gitcoin.co/0xpyk) has been approved to start work.**

Javascript based development using https://terra-money.github.io/terra.js/

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/dimensiondev/maskbook/5836/100028537).

**Comment by LindaMask** [comment]
@anish-mukherjee hey can you please reach out on telegram @lin_dao so I can take you through our bounty program?

**Comment by LindaMask** [comment]
@0xpyk has been approved for this bounty and there is a telegram group in place
