### ISSUE TITLE
[Bounty] Integrate Woofi Swap, A DEX into Mask Plugin

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#6087]
## Catalogue

- Platform
  - [ ] Gitcoin
  - [ ] Hackerlink
  - [x] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 1 week
- Bounty Size
  - [x] 1000 USDC or $MASK equivalent 

## Part 1: Problem Description
**Background** Woofi is a capital-efficient decentralized exchange (DEX) that is powered by institutional hedging and CeFi liquidity. WOOFi eliminates fees by allowing users to compare prices available on other platforms in real time. Woofi relies on market data from the WOO network to be frequently updated on the blockchain in order to replicate CeFi conditions. WOOFi does this by leveraging Chainlink’s oracle technology which is capable of maintaining consistent uptime even during the most volatile of market conditions. 

**Solution** Create a plugin that integrates Woofi on all chains into Mask. Woofi is available on BNB, Avalance and Fantom. The UI should be identical to other swaps.

![image](https://user-images.githubusercontent.com/94482490/163489625-dfdad7fc-504c-4e28-86c4-6cdb760436d5.png)
![image](https://user-images.githubusercontent.com/94482490/163489641-cadff11c-1a41-4ba5-946c-9aeabfdfcf90.png)

## Part 2: Resources
- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- [Woofi integration docs](https://learn.woo.org/woofi/dev-docs/how-to-integrate-woofi-swap)
- [Woofi Smart contract](https://learn.woo.org/woofi/dev-docs/contract)

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Woofi Discord: https://discord.com/invite/woonetwork

Please reach out to lin_DAO on Telegram and she will create a dedicated group with the Mask team to start the bounty process

Submission Requirements
Please include demo to show the integration is working.

**Comment by brymut** [comment]
Looking into this while I wait for feedback
