### ISSUE TITLE
[Bounty] Integrate Astar, a Multi-Chain Smart Contract into Mask Plugin 

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#6148]
## Catalogue

- Platform
  - [ ] Gitcoin
  - [ ] Hackerlink
  - [x] Mask
- Experience
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  - [x] 2 weeks
- Bounty Size
  - [x] $2000 USD or $MASK equivalent 

## Part 1: Problem Description

Astar Network connects the Polkadot ecosystem to Ethereum, Cosmos, and all major Layer 1 Blockchains. Astar Network supports dApps using multiple virtual machines WASM and EVM and offers the best technology and financial incentives via Build2Earn and Astar Incubation Program.

**Solution** 
Integrate Astar into Mask Plugin

**To Do** 
- Migrate the following applications to ASTAR：redpocket, balancerchecker, multical, tips.
- Basis function: connect, change wallet, presentation of visual elements, toast

**RPC**
- Network Name
- Astar Network
- Network URL
- https://evm.astar.network/
- Chain ID
- 592

## Part 2: Resources

- [Bounty Guide](https://github.com/DimensionDev/Maskbook/tree/master/docs/bounty-guide.md)
- [UI](https://astar.network/)
- https://astar.network/
- https://github.com/AstarNetwork

## Part 3: Contact and Support
@yisiliu @tzhan28 @LindaMask for ideas
@Jack-Works for implementations
Mask Network discord server: https://discord.gg/4Xccj7a75Q,
Astar Discord: https://discord.com/invite/Z3nC9U4

DM on telegram @lin_dao and she will create a dedicated group with the Mask team to start the bounty process

Submission Requirements
Please include demo to show the integration is working.
Have a working demo.
Clean code & tech design
Clear UI, easy to use and generally good user experience

**Comment by developerfred** [comment]
@LindaMask I would like to work on this integration

**Comment by LindaMask** [comment]
@developerfred is working on this.

**Comment by f8al3rr** [comment]
is this still open?

**Comment by LindaMask** [comment]
@f8al3rr yes but it is already taken

**Comment by yangwao** [comment]
Any progress on this?
