### ISSUE TITLE
Mask Pishing Detect [Demand] 

### ISSUE THREAD

**Issue by developerfred** [DimensionDev/Maskbook#6166]
## Catalogue

- [x] UI/UX
- [x] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

Currently it rains fraudulent airdrops and attack attempts thanks to https://github.com/MetaMask/eth-phishing-detect we were able to verify a malicious project in advance. I would like mask to protect its users from these malicious projects by replacing the post or just putting a big red warning tag.

ref
<img width="623" alt="Screenshot 2022-04-26 at 23 10 07" src="https://user-images.githubusercontent.com/57037080/165393250-58df0ad1-9e55-4584-8ec3-e3351c24ec54.png">

https://github.com/MetaMask/eth-phishing-detect/commit/bb9d873a8481592c46afb5774eb8ca89aa9de8bd
